import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PublicSolanaRpcProvider,SolanaRpcError,rpcEndpoint} from '../lib/rpc-provider';
import {selectHolderWork} from '../lib/market/scheduling';
test('FIFO priority uses one slot and remaining budget rotates tracked tokens',()=>{
 const tokens=[{mint:'a'},{mint:'b'},{mint:'c'}];const first=selectHolderWork(tokens,['c','b'],0,2);assert.deepEqual(first.candidates.map(t=>t.mint),['c','a']);assert.deepEqual(selectHolderWork(tokens,['c'],1,2).candidates.map(t=>t.mint),['c','b']);assert.deepEqual(selectHolderWork(tokens,[],2,2).candidates.map(t=>t.mint),['c','a']);assert.equal(selectHolderWork(tokens,['c'],0,0).candidates.length,0);
});
test('RPC serializes transaction requests across consumers',async()=>{const original=globalThis.fetch;let active=0,max=0;globalThis.fetch=async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,1));active--;return Response.json({result:{ok:true}});};try{const p=new PublicSolanaRpcProvider(()=> 'https://example.invalid');await Promise.all([p.request('getTransaction',[]),p.request('getTransaction',[]),p.request('getTransaction',[])]);assert.equal(max,1);}finally{globalThis.fetch=original;}});
test('rate limit opens circuit; classified errors never expose provider credentials',async()=>{const original=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests++;return new Response('private upstream details',{status:429});};try{const p=new PublicSolanaRpcProvider(()=> 'https://example.invalid/key-secret');for(let i=0;i<2;i++)await assert.rejects(p.request('getTransaction',[]),e=>e instanceof SolanaRpcError&&e.kind==='rate_limited'&&!e.message.includes('secret'));assert.equal(requests,1);}finally{globalThis.fetch=original;}});
test('null transaction and unsupported RPC version remain distinct diagnostics',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({result:null});await assert.rejects(new PublicSolanaRpcProvider().request('getTransaction',[]),e=>e instanceof SolanaRpcError&&e.kind==='not_found');globalThis.fetch=async()=>Response.json({error:{code:-32015,message:'private'}});await assert.rejects(new PublicSolanaRpcProvider().request('getTransaction',[]),e=>e instanceof SolanaRpcError&&e.kind==='rpc_error'&&e.code===-32015&&!e.message.includes('private'));}finally{globalThis.fetch=original;}});

test('method routing respects independent overrides and shared legacy configuration',()=>{
 const names=['SOLANA_RPC_URL','SOLANA_TRAFFIC_RPC_URL','SOLANA_HOLDER_RPC_URL'];const saved=names.map(n=>process.env[n]);
 try{for(const n of names)delete process.env[n];assert.equal(rpcEndpoint('getTransaction'),'https://solana-rpc.publicnode.com');assert.equal(rpcEndpoint('getProgramAccounts'),'https://api.mainnet-beta.solana.com');process.env.SOLANA_RPC_URL='shared';assert.equal(rpcEndpoint('getTransaction'),'shared');process.env.SOLANA_TRAFFIC_RPC_URL='traffic';process.env.SOLANA_HOLDER_RPC_URL='holders';assert.equal(rpcEndpoint('getSignaturesForAddress'),'traffic');assert.equal(rpcEndpoint('getTokenSupply'),'holders');}finally{names.forEach((n,i)=>{if(saved[i]==null)delete process.env[n];else process.env[n]=saved[i];});}
});
