"use client";
import {useState} from 'react';
import type {TrafficSummary} from '@/lib/market/traffic/summary';
const n=(v:number|null|undefined,s='')=>v==null?'—':`${v.toLocaleString(undefined,{maximumFractionDigits:1})}${s}`;
export default function TrafficCard({sample}:{sample?:TrafficSummary|null}){
 const [window,setWindow]=useState('15');
 if(!sample)return <details className="signal-disclosure signal-comparisons"><summary>Swap Traffic · изчаква извадка</summary><p className="signal-note">Awaiting background scans of this token’s most liquid pools.</p></details>;
 const w=sample.windows[window];
 const rows:[string,string][]=[['Buyer / seller wallets',`${n(w.buyers)} / ${n(w.sellers)}`],['Buy / sell swaps',`${n(w.buys)} / ${n(w.sells)}`],['Buy / sell USD · sample',`${n(w.buyUsd,' $')} / ${n(w.sellUsd,' $')}`],['Net USD · sample',n(w.netUsd,' $')],['First seen / returning buyers',`${n(w.newSampleBuyers)} / ${n(w.repeatSampleBuyers)}`],['Median / largest buy',`${n(w.medianBuyUsd,' $')} / ${n(w.largestBuyUsd,' $')}`],['Top 3 buyer share',n(w.top3BuyerSharePct,'%')],['Quick resale wallets ≤15m',n(w.quickResellers)],['Buyers still holding · checked',`${n(w.retainedBuyers)} / ${n(w.retentionChecked)}`],['Linked buyers · sampled evidence',n(w.linkedBuyers)]];
 const badge=sample.evidence==='usable'?'надеждна извадка':sample.evidence==='degraded'?'ограничени данни':sample.evidence==='sparse'?'малко разпознати сделки':'събира данни';
 return <details className="signal-disclosure signal-comparisons"><summary><span>Swap Traffic · {badge}</span><b>{n(sample.windows['15']?.buys)} ↑ / {n(sample.windows['15']?.sells)} ↓</b></summary><label> Window <select aria-label="Swap sample interval" value={window} onChange={e=>setWindow(e.target.value)}><option value="5">5m</option><option value="15">15m</option><option value="60">1h</option></select></label>
 <p className="signal-note">Window ends at scan: {new Date(sample.observedAt).toLocaleString()}. Sampled pools: {sample.pools?.length??1}; this is still partial market coverage.</p>
 <dl className="market-token-stats">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 <details className="signal-note"><summary>Покритие и обяснение</summary><p>Pools: {(sample.pools?.length?sample.pools:[sample.pool]).join(" · ")}</p><p>Retained scans: {sample.scans}; parsed: {sample.parsedTransactions}; recognized: {sample.recognizedTransactions} ({sample.directRecognizedTransactions} verified-direct / {sample.routedRecognizedTransactions} routed); unsupported: {sample.unrecognizedTransactions}; unavailable: {sample.unavailableTransactions}. Limited scans: {sample.limitedScans}{sample.rowLimitReached?'; row limit reached':''}.</p><p>RPC diagnostics: {Object.entries(sample.failures??{}).map(([k,v])=>`${k}: ${v}`).join(" · ")||"No recorded error classifications"}</p><p>{sample.note}</p><p>Returning buyers were seen before this window in retained samples. Retention is checked only against a recent holder observation after the purchase; unknown values remain —. Related wallets are evidence of a relationship, not proof of coordinated trading. Median/largest buys use only priced swaps.</p></details></details>;
}
