import fs from 'node:fs';
import ts from 'typescript';

// The Edge Function shares the same implementation, with no duplicated formulas.
const version = JSON.parse(fs.readFileSync('package-lock.json','utf8')).packages['node_modules/@supabase/supabase-js'].version;
const sources = ['lib/db.ts','lib/rpc-provider.ts','lib/solana-public.ts','lib/market/collect.ts','lib/market/signals.ts','lib/market/windows.ts','lib/market/sales.ts','lib/market/relationships.ts','lib/market/holders.ts','lib/market/traffic/programs.ts','lib/market/traffic/decode.ts','lib/market/traffic/summary.ts','lib/market/traffic/observe.ts','lib/market/scheduling.ts','lib/watchlist.ts','lib/watchlist-server.ts','lib/market/ingest.ts'];
let source = `import process from 'node:process';\nimport { Buffer } from 'node:buffer';\nimport { timingSafeEqual } from 'node:crypto';\n`;
for (const file of sources) source += fs.readFileSync(file,'utf8').replace(/^import .* from ['"](?:\.|@\/)[^'"]*['"];?\s*$/gm,'').replace('"@supabase/supabase-js"',`"npm:@supabase/supabase-js@${version}"`)+'\n';
source += `
const rpc = solanaRpc;
Deno.serve(async (req: Request) => {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 });
  const provided = req.headers.get('authorization') ?? '';
  if (!/^Bearer [a-f0-9-]{72}$/.test(provided)) return new Response('Unauthorized', { status: 401 });
  const { data, error } = await admin().from('market_worker_config').select('secret').eq('id', 1).single();
  const expected = 'Bearer ' + (data?.secret ?? '');
  if (error || Buffer.byteLength(provided) !== Buffer.byteLength(expected) || !timingSafeEqual(Buffer.from(provided), Buffer.from(expected))) return new Response('Unauthorized', { status: 401 });
  try { return Response.json(await ingestMarket()); }
  catch (error) { console.error('Snapshot worker failed', error instanceof Error ? error.message : 'upstream/database error'); return Response.json({ error: 'Snapshot worker failed; previous cache retained' }, { status: 502 }); }
});`;
const result = ts.transpileModule(source, { compilerOptions: { target:ts.ScriptTarget.ES2022, module:ts.ModuleKind.ES2022 } });
const indexPath='supabase/functions/market-snapshot/index.js';
const denoPath='supabase/functions/market-snapshot/deno.json';
const index='// Generated by npm run worker:bundle. Edit lib/market, not this file.\n'+result.outputText;
const deno=JSON.stringify({compilerOptions:{lib:['deno.ns','deno.window','esnext']}},null,2)+'\n';

if(process.argv.includes('--check')){
  const currentIndex=fs.existsSync(indexPath)?fs.readFileSync(indexPath,'utf8'):'';
  const currentDeno=fs.existsSync(denoPath)?fs.readFileSync(denoPath,'utf8'):'';
  if(currentIndex!==index||currentDeno!==deno){
    console.error('Generated market worker is stale. Run npm run worker:bundle and commit the result.');
    process.exit(1);
  }
  console.log('Generated market worker is in sync');
}else{
  fs.mkdirSync('supabase/functions/market-snapshot',{recursive:true});
  fs.writeFileSync(indexPath,index);
  fs.writeFileSync(denoPath,deno);
  console.log('Shared market worker generated');
}
