-- Archive wallets that fully exit a tracked token position.
create table if not exists public.exited_holders (
  id bigint generated by default as identity primary key,
  token_mint text not null references public.tokens(mint) on delete cascade,
  wallet text not null,
  bought_usd numeric default 0,
  sold_usd numeric default 0,
  first_activity timestamptz,
  last_activity timestamptz,
  exited_at timestamptz not null default now(),
  last_signature text,
  exit_side text,
  funder text,
  cluster_id int
);

create index if not exists exited_holders_token_wallet_idx
  on public.exited_holders (token_mint, wallet, exited_at desc);

create index if not exists exited_holders_token_exited_idx
  on public.exited_holders (token_mint, exited_at desc);

alter table public.exited_holders enable row level security;

drop policy if exists "public read" on public.exited_holders;
create policy "public read" on public.exited_holders
  for select using (true);
