create table if not exists public.client_error_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  created_at timestamptz not null default now(),
  kind text not null check (char_length(kind) <= 60),
  route text not null check (char_length(route) <= 240),
  message text not null check (char_length(message) <= 900),
  stack text,
  source text,
  app_version text,
  user_agent text
);

create index if not exists client_error_events_created_at_idx on public.client_error_events(created_at desc);
alter table public.client_error_events enable row level security;
revoke all on public.client_error_events from anon, authenticated;
