// Generated by npm run worker:bundle. Edit lib/market, not this file.
import process from 'node:process';
import { Buffer } from 'node:buffer';
import { timingSafeEqual } from 'node:crypto';
import { createClient } from "npm:@supabase/supabase-js@2.117.2";
// Само server-side (service role).
export const admin = () => createClient((process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL), process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
export class PublicSolanaRpcProvider {
    endpoint;
    constructor(endpoint = () => process.env.SOLANA_RPC_URL || 'https://api.mainnet-beta.solana.com') {
        this.endpoint = endpoint;
    }
    async request(method, params) {
        const response = await fetch(this.endpoint(), {
            signal: AbortSignal.timeout(15_000), method: 'POST', cache: 'no-store',
            headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
        });
        if (!response.ok)
            throw new Error(`Solana RPC failed: ${response.status}`);
        const data = await response.json();
        if (data.error)
            throw new Error(data.error.message || `Solana RPC error ${data.error.code ?? ''}`);
        if (data.result == null)
            throw new Error('Solana RPC returned no result');
        return data.result;
    }
}
let rpcProvider = new PublicSolanaRpcProvider();
export const setSolanaRpcProvider = (provider) => { rpcProvider = provider; };
export const solanaRpc = (method, params) => rpcProvider.request(method, params);
const TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
const TOKEN_2022_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
export async function getRpcHealth() {
    try {
        const result = await rpc("getHealth", []);
        return { ok: result === "ok", result };
    }
    catch (error) {
        return { ok: false, result: error instanceof Error ? error.message : "RPC error" };
    }
}
export async function fetchPublicSupply(mint) {
    const result = await rpc("getTokenSupply", [mint, { commitment: "confirmed" }]);
    const value = result?.value;
    return {
        supply: Number(value?.uiAmountString ?? value?.uiAmount ?? 0),
        decimals: Number(value?.decimals ?? 0),
    };
}
const BASE58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function base58(bytes) {
    let value = 0n;
    for (const byte of bytes)
        value = (value << 8n) + BigInt(byte);
    let out = "";
    while (value > 0n) {
        const mod = Number(value % 58n);
        out = BASE58[mod] + out;
        value /= 58n;
    }
    let leading = 0;
    while (leading < bytes.length && bytes[leading] === 0)
        leading++;
    return "1".repeat(leading) + (out || (leading ? "" : "1"));
}
async function holderAccounts(programId, mint) {
    // Token account layout starts with mint[32], owner[32], amount[u64].
    // Slice only owner+amount instead of downloading every full token account.
    // This drastically reduces bandwidth and pressure on the public RPC.
    const result = await rpc("getProgramAccounts", [
        programId,
        {
            commitment: "confirmed",
            encoding: "base64",
            dataSlice: { offset: 32, length: 40 },
            filters: [{ memcmp: { offset: 0, bytes: mint } }],
        },
    ]);
    return result.flatMap((row) => {
        const encoded = Array.isArray(row?.account?.data) ? row.account.data[0] : null;
        if (!encoded || typeof encoded !== "string")
            return [];
        try {
            const buf = Buffer.from(encoded, "base64");
            if (buf.length < 40)
                return [];
            const owner = base58(buf.subarray(0, 32));
            const raw = buf.readBigUInt64LE(32);
            if (!owner || raw <= 0n)
                return [];
            return [{ wallet: owner, raw }];
        }
        catch {
            return [];
        }
    });
}
export async function fetchPublicHolders(mint, maxAgeMs = 5 * 60 * 1000) {
    const db = admin();
    const cacheKey = `public-rpc:holders:${mint}`;
    const { data: cached } = await db
        .from("api_cache")
        .select("payload,updated_at")
        .eq("cache_key", cacheKey)
        .maybeSingle();
    if (cached?.payload && cached?.updated_at) {
        const age = Date.now() - new Date(cached.updated_at).getTime();
        if (age <= maxAgeMs) {
            const rows = Array.isArray(cached.payload) ? cached.payload : [];
            return rows.map((h) => ({ wallet: String(h.wallet), raw: BigInt(String(h.raw)) }));
        }
    }
    let rows = [];
    let lastError = null;
    for (const program of [TOKEN_PROGRAM, TOKEN_2022_PROGRAM]) {
        try {
            const part = await holderAccounts(program, mint);
            rows.push(...part);
            if (part.length)
                break;
        }
        catch (error) {
            lastError = error;
        }
    }
    if (!rows.length && lastError)
        throw lastError;
    const byOwner = new Map();
    for (const row of rows)
        byOwner.set(row.wallet, (byOwner.get(row.wallet) ?? 0n) + row.raw);
    rows = [...byOwner.entries()].map(([wallet, raw]) => ({ wallet, raw }));
    await db.from("api_cache").upsert({
        cache_key: cacheKey,
        payload: rows.map((h) => ({ wallet: h.wallet, raw: h.raw.toString() })),
        updated_at: new Date().toISOString(),
    });
    return rows;
}
export async function fetchDexScreenerToken(mint) {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${encodeURIComponent(mint)}`, {
        headers: { accept: "application/json" },
        cache: "no-store",
    });
    if (!res.ok)
        throw new Error(`DexScreener failed: ${res.status}`);
    const json = await res.json();
    const pairs = Array.isArray(json?.pairs) ? json.pairs.filter((p) => p?.chainId === "solana") : [];
    const best = pairs.sort((a, b) => Number(b?.liquidity?.usd ?? 0) - Number(a?.liquidity?.usd ?? 0))[0] ?? null;
    return {
        priceUsd: Number(best?.priceUsd ?? 0),
        name: best?.baseToken?.name ?? null,
        symbol: best?.baseToken?.symbol ?? null,
        marketCap: Number(best?.marketCap ?? best?.fdv ?? 0),
        liquidityUsd: Number(best?.liquidity?.usd ?? 0),
        volume24h: Number(best?.volume?.h24 ?? 0),
    };
}
export async function fetchRecentSignatures(address, limit = 8) {
    return rpc("getSignaturesForAddress", [
        address,
        { limit, commitment: "confirmed" },
    ]);
}
export async function fetchParsedTransaction(signature) {
    try {
        return await rpc("getTransaction", [
            signature,
            {
                commitment: "confirmed",
                encoding: "jsonParsed",
                maxSupportedTransactionVersion: 0,
            },
        ]);
    }
    catch {
        return null;
    }
}
const SOL = "So11111111111111111111111111111111111111112";
async function getJson(url) {
    try {
        const r = await fetch(url, { cache: "no-store", signal: AbortSignal.timeout(12_000), headers: { accept: "application/json" } });
        if (!r.ok)
            return null;
        return await r.json();
    }
    catch {
        return null;
    }
}
export async function collectMarket(previousPayload, trackedMints = []) {
    const [profiles, boosts] = await Promise.all([
        getJson("https://api.dexscreener.com/token-profiles/latest/v1"),
        getJson("https://api.dexscreener.com/token-boosts/top/v1"),
    ]);
    const profileIcon = new Map();
    for (const p of profiles ?? []) {
        if (p.chainId !== "solana" || !p.tokenAddress)
            continue;
        const icon = p.icon || p.imageUrl;
        if (icon)
            profileIcon.set(p.tokenAddress, icon);
    }
    const boostMap = new Map();
    for (const b of boosts ?? []) {
        if (b.chainId !== "solana" || !b.tokenAddress)
            continue;
        boostMap.set(b.tokenAddress, Math.max(Number(b.totalAmount ?? b.amount ?? 0), boostMap.get(b.tokenAddress) ?? 0));
    }
    const addresses = [];
    const push = (a) => {
        if (!a || a === SOL || addresses.includes(a))
            return;
        addresses.push(a);
    };
    for (const b of boosts ?? [])
        if (b.chainId === "solana")
            push(b.tokenAddress);
    for (const p of profiles ?? [])
        if (p.chainId === "solana")
            push(p.tokenAddress);
    const tracked = (previousPayload?.tokens ?? []).map((t) => String(t.mint));
    const picked = [...new Set([...trackedMints.slice(0, 20), ...tracked.slice(0, 50), ...addresses, ...tracked])].slice(0, 100);
    const chunks = [];
    for (let i = 0; i < picked.length; i += 30)
        chunks.push(picked.slice(i, i + 30));
    const batch = await Promise.all(chunks.map((chunk) => getJson(`https://api.dexscreener.com/tokens/v1/solana/${chunk.join(",")}`)));
    const best = new Map();
    for (const pairs of batch) {
        for (const p of pairs ?? []) {
            if (p.chainId !== "solana" || !p.baseToken?.address)
                continue;
            const mint = p.baseToken.address;
            const prev = best.get(mint);
            if (!prev || Number(p.liquidity?.usd ?? 0) > Number(prev.liquidity?.usd ?? 0))
                best.set(mint, p);
        }
    }
    if (!best.size)
        throw new Error("Market sources unavailable; retaining last successful snapshot");
    const tokens = [...best.entries()].map(([mint, p]) => {
        const buys1h = Number(p.txns?.h1?.buys ?? 0);
        const sells1h = Number(p.txns?.h1?.sells ?? 0);
        return {
            mint,
            name: p.baseToken?.name ?? null,
            symbol: p.baseToken?.symbol ?? null,
            dex: p.dexId ?? null,
            pairAddress: p.pairAddress ?? null,
            quoteMint: p.quoteToken?.address ?? null,
            quoteSymbol: p.quoteToken?.symbol ?? null,
            priceUsd: Number(p.priceUsd ?? 0),
            marketCap: Number(p.marketCap ?? p.fdv ?? 0),
            fdv: p.fdv == null ? null : Number(p.fdv),
            liquidityUsd: Number(p.liquidity?.usd ?? 0),
            volume1h: Number(p.volume?.h1 ?? 0),
            volume24h: Number(p.volume?.h24 ?? 0),
            buys1h,
            sells1h,
            trades1h: buys1h + sells1h,
            priceChange1h: Number(p.priceChange?.h1 ?? 0),
            priceChange24h: Number(p.priceChange?.h24 ?? 0),
            boost: boostMap.get(mint) ?? 0,
            imageUrl: p.info?.imageUrl ?? profileIcon.get(mint) ?? null,
            hypeScore: 0,
            traffic: "flat",
            netFlowUsd1h: 0,
            activityDelta: 0,
            hypeDelta: 0,
            volumeDelta: 0,
        };
    })
        .filter((t) => t.marketCap > 0 || t.liquidityUsd > 0 || t.volume1h > 0)
        .sort((a, b) => (b.volume1h + b.trades1h * 30 + b.boost * 50) - (a.volume1h + a.trades1h * 30 + a.boost * 50))
        .slice(0, 100);
    for (const t of tokens) {
        // Fixed scales keep Hype comparable when the discovery universe changes.
        const tradeNorm = Math.min(1, Math.log10(t.trades1h + 1) / 4);
        const volumeNorm = Math.min(1, Math.log10(t.volume1h + 1) / 6);
        const boostNorm = Math.min(1, Math.log10(t.boost + 1) / 3);
        const buyRatio = t.trades1h ? t.buys1h / t.trades1h : 0;
        const momentumNorm = Math.max(0, Math.min(1, (t.priceChange1h + 12) / 36));
        t.hypeScore = Math.round((tradeNorm * .30 + buyRatio * .24 + momentumNorm * .22 + boostNorm * .14 + volumeNorm * .10) * 100);
        const imbalance = (t.buys1h - t.sells1h) / Math.max(1, t.trades1h);
        t.traffic = imbalance > .16 ? "in" : imbalance < -.16 ? "out" : "flat";
    }
    const previousTokens = new Map();
    for (const t of Array.isArray(previousPayload?.tokens) ? previousPayload.tokens : []) {
        if (t?.mint)
            previousTokens.set(String(t.mint), t);
    }
    const recentEvents = [];
    for (const t of tokens) {
        const prev = previousTokens.get(t.mint);
        if (!prev)
            continue;
        const deltaTrades = t.trades1h - Number(prev.trades1h ?? 0);
        const deltaVolume = t.volume1h - Number(prev.volume1h ?? 0);
        const previousHype = Number(prev.hypeScore ?? 0);
        t.activityDelta = deltaTrades;
        t.volumeDelta = deltaVolume;
        t.hypeDelta = t.hypeScore - previousHype;
        if (deltaTrades === 0 && Math.abs(deltaVolume) < 1 && t.hypeDelta === 0)
            continue;
        const kind = deltaTrades > 2 || t.hypeDelta >= 5 ? "surge" :
            deltaTrades < -2 || t.hypeDelta <= -5 ? "cooldown" :
                t.traffic === "in" ? "buy-pressure" : "sell-pressure";
        recentEvents.push({
            mint: t.mint,
            symbol: t.symbol,
            kind,
            deltaTrades,
            deltaVolume,
            hypeDelta: t.hypeDelta,
            at: new Date().toISOString(),
        });
    }
    recentEvents.sort((a, b) => (Math.abs(b.deltaTrades) * 100 + Math.abs(b.hypeDelta) * 10 + Math.abs(b.deltaVolume) / 1000) -
        (Math.abs(a.deltaTrades) * 100 + Math.abs(a.hypeDelta) * 10 + Math.abs(a.deltaVolume) / 1000));
    const shown = new Set(tokens.map((t) => t.mint));
    const core = new Set([
        SOL,
        "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        "Es9vMFrzaCERmJfrF4H2FYDgHkmPG8TbQnYQ8V4a8Qj",
    ]);
    const marketFlows = tokens.flatMap((t) => {
        if (!t.quoteMint || (!shown.has(t.quoteMint) && !core.has(t.quoteMint)))
            return [];
        const totalTrades = Math.max(1, t.buys1h + t.sells1h);
        const buyShare = t.buys1h / totalTrades;
        const sellShare = t.sells1h / totalTrades;
        const out = [];
        const buyUsd = t.volume1h * buyShare;
        const sellUsd = t.volume1h * sellShare;
        if (buyUsd > 1)
            out.push({
                from: t.quoteMint,
                to: t.mint,
                usd1h: buyUsd,
                trades1h: t.buys1h,
                kind: "buy",
                dex: t.dex,
                source: "market",
            });
        if (sellUsd > 1)
            out.push({
                from: t.mint,
                to: t.quoteMint,
                usd1h: sellUsd,
                trades1h: t.sells1h,
                kind: "sell",
                dex: t.dex,
                source: "market",
            });
        return out;
    });
    const byQuote = new Map();
    for (const t of tokens) {
        if (!t.quoteMint)
            continue;
        const list = byQuote.get(t.quoteMint) ?? [];
        list.push(t);
        byQuote.set(t.quoteMint, list);
    }
    const rotationFlows = [];
    for (const group of byQuote.values()) {
        const outTokens = group
            .filter((t) => t.sells1h > t.buys1h && t.volume1h > 100)
            .sort((a, b) => (b.sells1h - b.buys1h) - (a.sells1h - a.buys1h))
            .slice(0, 5);
        const inTokens = group
            .filter((t) => t.buys1h > t.sells1h && t.volume1h > 100)
            .sort((a, b) => (b.buys1h - b.sells1h) - (a.buys1h - a.sells1h))
            .slice(0, 5);
        for (const from of outTokens) {
            const sellShare = from.sells1h / Math.max(1, from.trades1h);
            const sellUsd = from.volume1h * sellShare;
            for (const to of inTokens) {
                if (from.mint === to.mint)
                    continue;
                const buyShare = to.buys1h / Math.max(1, to.trades1h);
                const buyUsd = to.volume1h * buyShare;
                const usd1h = Math.min(sellUsd, buyUsd) * 0.30;
                if (usd1h < 150)
                    continue;
                const confidence = Math.min(0.82, 0.42 + Math.min(sellShare, buyShare) * 0.36);
                rotationFlows.push({
                    from: from.mint,
                    to: to.mint,
                    usd1h,
                    trades1h: Math.min(from.sells1h, to.buys1h),
                    kind: "rotation",
                    dex: to.dex,
                    source: "inferred",
                    confidence,
                });
            }
        }
    }
    const flows = [...marketFlows, ...rotationFlows]
        .sort((a, b) => (b.usd1h * ("confidence" in b ? Number(b.confidence ?? 1) : 1)) - (a.usd1h * ("confidence" in a ? Number(a.confidence ?? 1) : 1)))
        .slice(0, 220);
    const netFlow = new Map();
    for (const flow of flows) {
        if (!shown.has(flow.from) || !shown.has(flow.to))
            continue;
        netFlow.set(flow.from, (netFlow.get(flow.from) ?? 0) - flow.usd1h);
        netFlow.set(flow.to, (netFlow.get(flow.to) ?? 0) + flow.usd1h);
    }
    for (const token of tokens)
        token.netFlowUsd1h = netFlow.get(token.mint) ?? 0;
    const hotPath = [...rotationFlows]
        .sort((a, b) => (b.usd1h * b.confidence) - (a.usd1h * a.confidence))
        .slice(0, 6)
        .map((f) => ({
        from: f.from,
        to: f.to,
        score: Math.round(f.usd1h * f.confidence),
        confidence: f.confidence,
    }));
    const observedTrades1h = tokens.reduce((sum, t) => sum + t.trades1h, 0);
    const payload = {
        fetchedAt: new Date().toISOString(),
        tokens,
        flows,
        hotPath,
        recentEvents: recentEvents.slice(0, 12),
        network: {
            swaps1h: observedTrades1h,
            source: "dexscreener",
        },
        live: true,
    };
    return payload;
}
const finite = (n) => typeof n === 'number' && Number.isFinite(n);
export const percentChange = (value, previous) => previous > 0 ? (value - previous) / previous * 100 : null;
export function deriveSignals(t, previous, at, baselineAt) {
    const minutes = baselineAt ? (Date.parse(at) - Date.parse(baselineAt)) / 60_000 : 0;
    const comparable = previous && minutes > 0 && minutes <= 60 && previous.pairAddress === t.pairAddress;
    const hypeDelta = comparable ? (t.hypeScore ?? 0) - (previous.hypeScore ?? 0) : null;
    const volumeDelta = comparable ? (t.volume1h ?? 0) - (previous.volume1h ?? 0) : null;
    const volumeVelocity = volumeDelta == null ? null : volumeDelta / minutes;
    const liquidityChange = comparable ? (t.liquidityUsd ?? 0) - (previous.liquidityUsd ?? 0) : null;
    const liquidityChangePct = comparable ? percentChange(t.liquidityUsd ?? 0, previous.liquidityUsd ?? 0) : null;
    const trades = (t.buys1h ?? 0) + (t.sells1h ?? 0);
    const liquidityWarning = liquidityChangePct != null && liquidityChangePct <= -25 && (previous?.liquidityUsd ?? 0) >= 5000;
    const riskFactors = [];
    const factor = (label, points, value) => riskFactors.push({ label, points: Math.round(points), value });
    if ((t.liquidityUsd ?? 0) < 10000)
        factor('Low liquidity (< $10k)', 20, t.liquidityUsd ?? 0);
    if (liquidityWarning)
        factor('Liquidity dropped ≥25%', 25, liquidityChangePct);
    if (finite(t.top10SupplyPct) && t.top10SupplyPct > 40)
        factor('Top 10 concentration (pool/program owners included)', Math.min(20, (t.top10SupplyPct - 40) * .4), t.top10SupplyPct);
    if (finite(t.largestHolderPct) && t.largestHolderPct > 10)
        factor('Large holder dominance', Math.min(20, (t.largestHolderPct - 10)), t.largestHolderPct);
    if (finite(t.linkedSupplyPct) && t.linkedSupplyPct > 10)
        factor('Linked-wallet supply concentration', Math.min(15, (t.linkedSupplyPct - 10) * .5), t.linkedSupplyPct);
    else if (finite(t.suspiciousWallets) && t.suspiciousWallets > 0)
        factor('Wallet relationship evidence', Math.min(10, t.suspiciousWallets * 2), t.suspiciousWallets);
    if (trades > 20 && (t.buys1h ?? 0) / trades < .3)
        factor('Strong sell pressure', 15, (t.sells1h ?? 0) / trades * 100);
    const fdvLiquidityRatio = finite(t.fdv) && t.fdv > 0 && (t.liquidityUsd ?? 0) > 0 ? t.fdv / (t.liquidityUsd) : null;
    if (fdvLiquidityRatio != null && fdvLiquidityRatio > 100)
        factor('FDV / liquidity imbalance', Math.min(15, Math.log10(fdvLiquidityRatio / 100) * 15 + 5), fdvLiquidityRatio);
    const risk = riskFactors.reduce((n, f) => n + f.points, 0);
    const reasons = riskFactors.map(f => f.label);
    const hypeVelocity = hypeDelta == null ? null : hypeDelta / minutes;
    const hypeAcceleration = hypeVelocity != null && finite(previous?.hypeVelocity) ? (hypeVelocity - previous.hypeVelocity) / minutes : null;
    const acceleration = volumeVelocity != null && finite(previous?.volumeVelocity) ? (volumeVelocity - previous.volumeVelocity) / minutes : null;
    return { hypeDelta, hypeVelocity, hypeAcceleration, fdvLiquidityRatio, riskFactors,
        volumeDelta, volumeVelocity, volumeAcceleration: acceleration, liquidityChange, liquidityChangePct,
        buyPressure: trades ? (t.buys1h ?? 0) / trades * 100 : null,
        liquidityWarning, baselineAt: comparable ? baselineAt : null,
        riskScore: Math.round(Math.min(100, risk)), riskReasons: reasons,
        riskCoverage: finite(t.top10SupplyPct) ? 'market + observed holders (heuristic)' : 'market only; holder risk unknown' };
}
export function evaluateAlerts(t, previous, at) {
    const alerts = [];
    const add = (kind, value, message, severity = 'info') => alerts.push({
        id: `${t.mint}:${kind}:${at}`, mint: t.mint, symbol: t.symbol ?? null, kind, severity, value, message, at,
        deltaTrades: 0, deltaVolume: t.volumeDelta ?? 0, hypeDelta: t.hypeDelta ?? 0
    });
    if ((t.hypeScore ?? 0) >= 70 && (previous?.hypeScore ?? 0) < 70)
        add('hype-threshold', t.hypeScore, 'Hype crossed 70/100');
    if ((t.hypeVelocity ?? 0) >= 3 && (previous?.hypeVelocity ?? 0) < 3)
        add('hype-velocity', t.hypeVelocity, 'Hype rises ≥3 points/min');
    if ((t.hypeAcceleration ?? 0) >= .3 && (previous?.hypeAcceleration ?? 0) < .3)
        add('hype-acceleration', t.hypeAcceleration, 'Hype velocity accelerates ≥0.3 points/min²');
    if ((t.hypeDelta ?? 0) >= 5 && (previous?.hypeDelta ?? 0) < 5)
        add('hype', t.hypeDelta, 'Hype increased ≥5 points');
    const holderGrowth = t.holderWindows?.['5']?.holderGrowthPct;
    const holderMinutes = t.holderBaselineAt && t.holderObservedAt ? (Date.parse(t.holderObservedAt) - Date.parse(t.holderBaselineAt)) / 60000 : null;
    const fastHolders = holderGrowth ?? (holderMinutes != null && holderMinutes <= 8 ? t.holderGrowthPct : null);
    if ((fastHolders ?? 0) >= 5 && t.holderObservedAt !== previous?.holderObservedAt)
        add('holder-growth', fastHolders, 'Observed holders grew ≥5% over roughly 5m');
    if (finite(t.buyPressure) && t.buyPressure >= 70 && (t.buys1h ?? 0) + (t.sells1h ?? 0) >= 20 && (previous?.buyPressure ?? 0) < 70)
        add('buy-pressure', t.buyPressure, 'Buy count share crossed 70%');
    if (t.liquidityWarning && !previous?.liquidityWarning)
        add('liquidity-disappearing', t.liquidityChangePct, 'Liquidity dropped ≥25%', 'critical');
    else if (finite(t.liquidityChangePct) && t.liquidityChangePct >= 20 && (previous?.liquidityChangePct ?? 0) < 20)
        add('liquidity', t.liquidityChangePct, 'Liquidity increased ≥20%');
    if (t.holderObservedAt !== previous?.holderObservedAt) {
        if ((t.whaleEnter ?? 0) > 0)
            add('whale-enter', t.whaleEnter, 'Owners crossed into ≥1% supply positions (includes program owners)');
        if ((t.whaleExit ?? 0) > 0)
            add('whale-exit', t.whaleExit, 'Owners left ≥1% supply positions', 'warning');
    }
    if (t.holderObservedAt !== previous?.holderObservedAt)
        for (const sale of t.topHolderSales ?? []) {
            if ((previous?.topHolderSales ?? []).some(p => p.signature === sale.signature && p.wallet === sale.wallet))
                continue;
            add('top-holder-selling', sale.amount, `Top owner ${sale.wallet.slice(0, 6)} has swap-like outflow; inspect ${sale.signature}`, 'warning');
            alerts.at(-1).id = `${t.mint}:top-holder-selling:${sale.wallet}:${sale.signature}`;
        }
    return alerts;
}
export const moverCategories = [
    { key: 'hypeVelocity', label: 'Hype Movers', unit: 'H/min' },
    { key: 'holderGrowthPct', label: 'Holder Movers', unit: '%' },
    { key: 'volumeAcceleration', label: 'Volume Movers', unit: '$/min²' },
    { key: 'liquidityChangePct', label: 'Liquidity Movers', unit: '%' },
    { key: 'smartMoneyFlowUsd', label: 'Smart Money Movers', unit: '$ observed whale balance Δ' },
];
export function rankMovers(tokens, key) {
    return tokens.filter(t => finite(t[key])).sort((a, b) => Math.abs(b[key]) - Math.abs(a[key]));
}
export function compareMarketWindows(token, at, baselines) {
    const windows = {};
    for (const b of baselines) {
        if (b.mint !== token.mint || b.payload.pairAddress !== token.pairAddress)
            continue;
        windows[String(b.window_minutes)] = { baselineAt: b.observed_at, observedAt: at, elapsedMinutes: (Date.parse(at) - Date.parse(b.observed_at)) / 60000,
            hypeDelta: (token.hypeScore ?? 0) - (b.payload.hypeScore ?? 0),
            volumeChangePct: percentChange(token.volume1h ?? 0, b.payload.volume1h ?? 0),
            liquidityChangePct: percentChange(token.liquidityUsd ?? 0, b.payload.liquidityUsd ?? 0),
            priceChangePct: percentChange(token.priceUsd ?? 0, b.payload.priceUsd ?? 0) };
    }
    return windows;
}
const QUOTES = new Set(['So11111111111111111111111111111111111111112', 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v', 'Es9vMFrzaCERmJfrF4H2FYDgHkmPG8TbQnYQ8V4a8Qj']);
/** Swap-like evidence only: a token transfer alone must never be labelled selling. */
export function detectSwapLikeSale(tx, mint, wallet, since) {
    if (!tx || tx.meta?.err || !tx.blockTime || tx.blockTime * 1000 <= Date.parse(since))
        return null;
    const delta = new Map();
    for (const [key, sign] of [['preTokenBalances', -1], ['postTokenBalances', 1]])
        for (const row of tx.meta?.[key] ?? []) {
            if (row.owner !== wallet)
                continue;
            const amount = Number(row.uiTokenAmount?.uiAmountString ?? row.uiTokenAmount?.uiAmount ?? 0);
            delta.set(row.mint, (delta.get(row.mint) ?? 0) + sign * amount);
        }
    const loss = -(delta.get(mint) ?? 0);
    if (loss <= 0 || ![...delta].some(([quote, amount]) => quote !== mint && QUOTES.has(quote) && amount > 0))
        return null;
    const signature = tx.transaction?.signatures?.[0];
    if (!signature)
        return null;
    return { wallet, signature: String(signature), amount: loss, at: new Date(tx.blockTime * 1000).toISOString() };
}
// Bounded sample, never a claim that every holder has been analyzed.
export async function sampleWalletRelationships(balances, mint, since, previousLargest) {
    const sample = [...balances].sort((a, b) => b.balance - a.balance).slice(0, 4);
    if (previousLargest && !sample.some(h => h.wallet === previousLargest))
        sample[sample.length - 1] = { wallet: previousLargest, balance: 0 };
    const sales = [];
    const funders = new Map();
    const signatures = new Map();
    let analyzed = 0;
    await Promise.all(sample.map(async (h) => {
        const recent = await fetchRecentSignatures(h.wallet, 2).catch(() => null);
        if (!recent)
            return;
        const txs = await Promise.all(recent.filter(s => !s.err).map(s => fetchParsedTransaction(s.signature)));
        if (!txs.some(Boolean))
            return;
        analyzed++;
        for (const tx of txs) {
            if (mint && since) {
                const sale = detectSwapLikeSale(tx, mint, h.wallet, since);
                if (sale)
                    sales.push(sale);
            }
            const instructions = [...(tx?.transaction?.message?.instructions ?? []), ...(tx?.meta?.innerInstructions ?? []).flatMap((x) => x.instructions ?? [])];
            for (const ix of instructions) {
                if (ix?.program !== 'system' || ix.parsed?.type !== 'transfer')
                    continue;
                const info = ix.parsed.info;
                if (info?.destination !== h.wallet || !info.source || info.source === h.wallet)
                    continue;
                const group = funders.get(info.source) ?? new Set();
                group.add(h.wallet);
                funders.set(info.source, group);
                const sigs = signatures.get(info.source) ?? new Set();
                sigs.add(String(tx.transaction.signatures?.[0] ?? ''));
                signatures.set(info.source, sigs);
            }
        }
    }));
    const wallets = new Set(balances.map(h => h.wallet));
    const evidence = [];
    for (const [funder, group] of funders) {
        if (group.size >= 2)
            evidence.push({ wallets: [...group], kind: 'common-funder', evidence: [`funder:${funder}`, ...(signatures.get(funder) ?? [])] });
        else if (wallets.has(funder))
            evidence.push({ wallets: [funder, ...group], kind: 'direct-funder', evidence: [...(signatures.get(funder) ?? [])] });
    }
    return { analyzed, sampled: sample.length, evidence, sales };
}
// One adapter boundary: replace this to use any indexer or RPC provider.
export const rpcHolderProvider = {
    async observe(mint) {
        const [{ supply, decimals }, holders] = await Promise.all([fetchPublicSupply(mint), fetchPublicHolders(mint, 0)]);
        if (!supply || !holders.length)
            throw new Error('Incomplete holder observation');
        return { supply, balances: holders.map(h => ({ wallet: h.wallet, balance: Number(h.raw) / 10 ** decimals })) };
    }
};
export async function observeHolders(mint, price, provider = rpcHolderProvider) {
    const db = admin();
    const key = `intelligence:holders:${mint}`;
    const { data: prev, error: readError } = await db.from('api_cache').select('payload,updated_at').eq('cache_key', key).maybeSingle();
    if (readError)
        throw readError;
    const current = await provider.observe(mint);
    const at = new Date().toISOString();
    const before = prev?.payload;
    const previous = before ? new Map(before.balances.map(h => [h.wallet, h.balance])) : null;
    const previousWhales = before ? new Set(before.balances.filter(h => h.balance / before.supply >= .01).map(h => h.wallet)) : null;
    const whales = new Set(current.balances.filter(h => h.balance / current.supply >= .01).map(h => h.wallet));
    const wallets = new Set(current.balances.map(h => h.wallet));
    const { data: links, error: linkError } = await db.from('wallet_links').select('wallet_a,wallet_b,kind,signal_count').eq('token_mint', mint);
    const linked = new Set(), suspicious = new Set();
    for (const link of links ?? []) {
        if (!wallets.has(link.wallet_a) || !wallets.has(link.wallet_b))
            continue;
        linked.add(link.wallet_a);
        linked.add(link.wallet_b);
        if (link.kind === 'funder' || link.signal_count >= 3) {
            suspicious.add(link.wallet_a);
            suspicious.add(link.wallet_b);
        }
    }
    const previousLargest = before ? [...before.balances].sort((a, b) => b.balance - a.balance)[0]?.wallet : undefined;
    const relationSample = await sampleWalletRelationships(current.balances, mint, prev?.updated_at, previousLargest);
    for (const group of relationSample.evidence)
        for (const wallet of group.wallets) {
            linked.add(wallet);
            suspicious.add(wallet);
        }
    const relationshipKnown = !!links?.length || relationSample.analyzed > 0;
    const whaleWallets = new Set([...whales, ...(previousWhales ?? [])]);
    const balanceNow = new Map(current.balances.map(h => [h.wallet, h.balance]));
    const sorted = [...current.balances].sort((a, b) => b.balance - a.balance);
    const { data: holderWindows, error: windowError } = await db.rpc('holder_window_comparisons', { p_mint: mint, p_at: at, p_wallets: [...wallets] });
    if (windowError)
        throw windowError;
    const metrics = {
        holderCount: current.balances.length,
        holderGrowth: previous ? current.balances.length - previous.size : null,
        holderGrowthPct: previous?.size ? (current.balances.length - previous.size) / previous.size * 100 : null,
        newHolders: previous ? current.balances.filter(h => !previous.has(h.wallet)).length : null,
        exitedHolders: previous ? [...previous.keys()].filter(w => !wallets.has(w)).length : null,
        largestHolderPct: sorted.length ? sorted[0].balance / current.supply * 100 : null,
        whaleConcentrationPct: current.balances.filter(h => whales.has(h.wallet)).reduce((n, h) => n + h.balance, 0) / current.supply * 100,
        linkedSupplyPct: relationshipKnown ? current.balances.filter(h => linked.has(h.wallet)).reduce((n, h) => n + h.balance, 0) / current.supply * 100 : null,
        holderWindows: holderWindows ?? {},
        topHolderSales: relationSample.sales,
        freshWallets: previous ? current.balances.filter(h => !previous.has(h.wallet)).length : null,
        top10SupplyPct: Math.min(100, [...current.balances].sort((a, b) => b.balance - a.balance).slice(0, 10).reduce((n, h) => n + h.balance, 0) / current.supply * 100),
        linkedWallets: !relationshipKnown ? null : linked.size,
        suspiciousWallets: !relationshipKnown ? null : suspicious.size,
        whaleEnter: previousWhales ? [...whales].filter(w => !previousWhales.has(w)).length : null,
        whaleExit: previousWhales ? [...previousWhales].filter(w => !whales.has(w)).length : null,
        smartMoneyFlowUsd: previous ? [...whaleWallets].reduce((n, w) => n + ((balanceNow.get(w) ?? 0) - (previous.get(w) ?? 0)) * price, 0) : null,
        relationshipCoverage: `${relationSample.analyzed}/${relationSample.sampled} largest owners sampled; stored links ${linkError ? 'unavailable' : links?.length ?? 0}. Recent transactions only.`,
        walletEvidence: relationSample.evidence,
        holderObservedAt: at, holderBaselineAt: previous ? prev.updated_at : null,
    };
    const { error } = await db.rpc('save_holder_observation', { p_mint: mint, p_at: at, p_payload: { ...current, metrics }, p_wallets: [...wallets] });
    if (error)
        throw error;
    return metrics;
}
import { randomUUID } from 'node:crypto';
export async function ingestMarket() {
    const db = admin(), lease = randomUUID();
    const claim = await db.rpc('claim_market_ingestion', { p_lease: lease });
    if (claim.error)
        throw claim.error;
    if (!claim.data)
        return { skipped: true, reason: 'Ingestion already running' };
    try {
        const storage = await db.rpc('enforce_market_storage_limit');
        if (storage.error)
            throw storage.error;
        const { data: cached, error } = await db.from('api_cache').select('payload').eq('cache_key', 'market:snapshot').maybeSingle();
        if (error)
            throw error;
        const previous = cached?.payload;
        const tracked = await db.from('tokens').select('mint').order('metadata_updated_at', { ascending: false, nullsFirst: false }).limit(20);
        if (tracked.error)
            throw tracked.error;
        const base = await collectMarket(previous, (tracked.data ?? []).map(t => t.mint));
        const prevTokens = new Map((previous?.tokens ?? []).map((t) => [t.mint, t]));
        const mints = base.tokens.map(t => t.mint);
        const { data: holders, error: holderError } = await db.from('api_cache').select('cache_key,payload,updated_at').in('cache_key', mints.map(m => `intelligence:holders:${m}`));
        if (holderError)
            throw holderError;
        const observations = new Map((holders ?? []).map(h => [h.cache_key.split(':').at(-1), h.payload.metrics]));
        const budget = Math.min(6, Math.max(0, Number(process.env.MARKET_HOLDER_BUDGET ?? 4) || 0));
        const cursor = Number(previous?.holderCursor ?? 0) % Math.max(1, mints.length);
        const failures = [];
        // Keep the two most active tracked tokens fresh each cycle; rotate the rest.
        const trackedSet = new Set((tracked.data ?? []).map(t => t.mint));
        const priority = base.tokens.filter(t => trackedSet.has(t.mint)).slice(0, 2);
        const rotation = base.tokens.filter(t => !priority.some(p => p.mint === t.mint));
        const candidates = [...priority];
        for (let i = 0; i < rotation.length && candidates.length < budget; i++)
            candidates.push(rotation[(cursor + i) % rotation.length]);
        let completed = 0;
        const started = Date.now();
        for (const t of candidates.slice(0, budget)) {
            if (Date.now() - started > 85_000)
                break;
            try {
                observations.set(t.mint, await observeHolders(t.mint, t.priceUsd));
            }
            catch {
                failures.push(t.mint);
            }
            completed++;
        }
        const at = new Date().toISOString();
        const baselines = await db.rpc('market_window_baselines', { p_mints: mints, p_at: at });
        if (baselines.error)
            throw baselines.error;
        const tokens = base.tokens.map(t => {
            const holder = observations.get(t.mint);
            const fresh = holder?.holderObservedAt && Date.now() - Date.parse(holder.holderObservedAt) < 60 * 60_000;
            const metrics = fresh ? holder : { holderCount: null, holderGrowth: null, holderGrowthPct: null, freshWallets: null, top10SupplyPct: null, linkedWallets: null, suspiciousWallets: null, whaleEnter: null, whaleExit: null, smartMoneyFlowUsd: null, holderObservedAt: holder?.holderObservedAt ?? null };
            if (!fresh)
                Object.assign(metrics, { newHolders: null, exitedHolders: null, largestHolderPct: null, whaleConcentrationPct: null, linkedSupplyPct: null, holderWindows: {}, topHolderSales: [] });
            const enriched = { ...t, ...metrics };
            return { ...enriched, windows: compareMarketWindows(enriched, at, (baselines.data ?? [])), ...deriveSignals(enriched, prevTokens.get(t.mint), at, previous?.fetchedAt),
                // Directional volume estimate based on trade counts, not measured capital transfers.
                netFlowUsd1h: t.volume1h * (t.buys1h - t.sells1h) / Math.max(1, t.trades1h) };
        });
        const alerts = tokens.flatMap(t => evaluateAlerts(t, prevTokens.get(t.mint), at));
        const history = await db.from('market_alerts').select('payload').gte('observed_at', new Date(Date.now() - 24 * 60 * 60_000).toISOString()).order('observed_at', { ascending: false }).limit(80);
        if (history.error)
            throw history.error;
        const seen = new Set();
        const recentAlerts = [...alerts, ...(history.data ?? []).map(r => r.payload)].filter(a => !seen.has(a.id) && !!seen.add(a.id)).slice(0, 80);
        const payload = { ...base, tokens, fetchedAt: at, holderCursor: (cursor + Math.max(0, completed - priority.length)) % Math.max(1, rotation.length),
            alerts: recentAlerts, recentEvents: base.recentEvents,
            storage: storage.data, ingestion: { holderCompleted: completed, priorityMints: priority.map(t => t.mint), holderBudget: budget, holderFailures: failures.length, source: 'server-worker', interval: '5m target; scheduler dependent' },
            metricNotes: { flow: 'USD estimate from rolling 1h trade counts', freshWallets: 'newly observed token holders; not wallet creation age', whales: 'owners ≥1% supply; pool/program owners included', smartMoney: 'whale balance change at current price; not verified swap flow', volumeAcceleration: 'acceleration of rolling 1h volume, USD/min²', risk: 'heuristic, not a security audit' } };
        const saved = await db.rpc('commit_market_snapshot', { p_lease: lease, p_payload: payload, p_alerts: alerts });
        if (saved.error)
            throw saved.error;
        return { ok: true, tokens: tokens.length, alerts: alerts.length, holderFailures: failures.length, fetchedAt: at };
    }
    finally {
        await db.rpc('release_market_ingestion', { p_lease: lease });
    }
}
const rpc = solanaRpc;
Deno.serve(async (req) => {
    if (req.method !== 'POST')
        return new Response('Method not allowed', { status: 405 });
    const provided = req.headers.get('authorization') ?? '';
    if (!/^Bearer [a-f0-9-]{72}$/.test(provided))
        return new Response('Unauthorized', { status: 401 });
    const { data, error } = await admin().from('market_worker_config').select('secret').eq('id', 1).single();
    const expected = 'Bearer ' + (data?.secret ?? '');
    if (error || Buffer.byteLength(provided) !== Buffer.byteLength(expected) || !timingSafeEqual(Buffer.from(provided), Buffer.from(expected)))
        return new Response('Unauthorized', { status: 401 });
    try {
        return Response.json(await ingestMarket());
    }
    catch (error) {
        console.error('Snapshot worker failed', error instanceof Error ? error.message : 'upstream/database error');
        return Response.json({ error: 'Snapshot worker failed; previous cache retained' }, { status: 502 });
    }
});
