// Generated by npm run worker:bundle. Edit lib/market, not this file.
import process from 'node:process';
import { Buffer } from 'node:buffer';
import { timingSafeEqual } from 'node:crypto';
import { createClient } from "npm:@supabase/supabase-js@2.117.2";
// Само server-side (service role).
export const admin = () => createClient((process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL), process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
export class SolanaRpcError extends Error {
    kind;
    status;
    code;
    constructor(kind, status, code) {
        super(`Solana RPC: ${kind}`);
        this.kind = kind;
        this.status = status;
        this.code = code;
    }
}
/** Method routing keeps indexed holder scans on their own provider. Explicit URLs override defaults. */
export function rpcEndpoint(method) {
    const traffic = method === 'getTransaction' || method === 'getSignaturesForAddress';
    return (traffic ? process.env.SOLANA_TRAFFIC_RPC_URL : process.env.SOLANA_HOLDER_RPC_URL) || process.env.SOLANA_RPC_URL || (traffic ? 'https://solana-rpc.publicnode.com' : 'https://api.mainnet-beta.solana.com');
}
export class PublicSolanaRpcProvider {
    endpoint;
    transactionQueue = Promise.resolve();
    cooldownUntil = 0;
    cooldownFailure = "rate_limited";
    constructor(endpoint = rpcEndpoint) {
        this.endpoint = endpoint;
    }
    request(method, params) {
        if (method !== 'getTransaction')
            return this.send(method, params);
        // All consumers share the same serial transaction lane, including holder relationships.
        const work = this.transactionQueue.catch(() => { }).then(() => this.send(method, params));
        this.transactionQueue = work;
        return work;
    }
    async send(method, params) {
        if (method === 'getTransaction' && Date.now() < this.cooldownUntil)
            throw new SolanaRpcError(this.cooldownFailure, this.cooldownFailure === 'rate_limited' ? 429 : undefined);
        let response;
        try {
            response = await fetch(this.endpoint(method), { signal: AbortSignal.timeout(15000), method: 'POST', cache: 'no-store', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) });
        }
        catch (e) {
            const kind = e instanceof Error && (e.name === 'TimeoutError' || e.name === 'AbortError') ? 'timeout' : 'network';
            if (method === 'getTransaction') {
                this.cooldownUntil = Date.now() + 60000;
                this.cooldownFailure = kind;
            }
            throw new SolanaRpcError(kind);
        }
        if (!response.ok) {
            if ([429, 401, 403].includes(response.status) && method === 'getTransaction') {
                this.cooldownUntil = Date.now() + 60000;
                this.cooldownFailure = response.status === 429 ? 'rate_limited' : 'forbidden';
            }
            throw new SolanaRpcError(response.status === 429 ? 'rate_limited' : [401, 403].includes(response.status) ? 'forbidden' : 'http_error', response.status);
        }
        let data;
        try {
            data = await response.json();
        }
        catch {
            throw new SolanaRpcError('invalid_response');
        }
        if (data.error)
            throw new SolanaRpcError('rpc_error', undefined, data.error.code);
        if (data.result == null)
            throw new SolanaRpcError('not_found');
        return data.result;
    }
}
let rpcProvider = new PublicSolanaRpcProvider();
export const setSolanaRpcProvider = (provider) => { rpcProvider = provider; };
export const solanaRpc = (method, params) => rpcProvider.request(method, params);
const TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
const TOKEN_2022_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
export async function getRpcHealth() {
    try {
        const result = await rpc("getHealth", []);
        return { ok: result === "ok", result };
    }
    catch (error) {
        return { ok: false, result: error instanceof Error ? error.message : "RPC error" };
    }
}
export async function fetchPublicSupply(mint) {
    const result = await rpc("getTokenSupply", [mint, { commitment: "confirmed" }]);
    const value = result?.value;
    return {
        supply: Number(value?.uiAmountString ?? value?.uiAmount ?? 0),
        decimals: Number(value?.decimals ?? 0),
    };
}
const BASE58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function base58(bytes) {
    let value = 0n;
    for (const byte of bytes)
        value = (value << 8n) + BigInt(byte);
    let out = "";
    while (value > 0n) {
        const mod = Number(value % 58n);
        out = BASE58[mod] + out;
        value /= 58n;
    }
    let leading = 0;
    while (leading < bytes.length && bytes[leading] === 0)
        leading++;
    return "1".repeat(leading) + (out || (leading ? "" : "1"));
}
async function holderAccounts(programId, mint) {
    // Token account layout starts with mint[32], owner[32], amount[u64].
    // Slice only owner+amount instead of downloading every full token account.
    // This drastically reduces bandwidth and pressure on the public RPC.
    const result = await rpc("getProgramAccounts", [
        programId,
        {
            commitment: "confirmed",
            encoding: "base64",
            dataSlice: { offset: 32, length: 40 },
            filters: [{ memcmp: { offset: 0, bytes: mint } }],
        },
    ]);
    return result.flatMap((row) => {
        const encoded = Array.isArray(row?.account?.data) ? row.account.data[0] : null;
        if (!encoded || typeof encoded !== "string")
            return [];
        try {
            const buf = Buffer.from(encoded, "base64");
            if (buf.length < 40)
                return [];
            const owner = base58(buf.subarray(0, 32));
            const raw = buf.readBigUInt64LE(32);
            if (!owner || raw <= 0n)
                return [];
            return [{ wallet: owner, raw }];
        }
        catch {
            return [];
        }
    });
}
export async function fetchPublicHolders(mint, maxAgeMs = 5 * 60 * 1000) {
    const db = admin();
    const cacheKey = `public-rpc:holders:${mint}`;
    const { data: cached } = await db
        .from("api_cache")
        .select("payload,updated_at")
        .eq("cache_key", cacheKey)
        .maybeSingle();
    if (cached?.payload && cached?.updated_at) {
        const age = Date.now() - new Date(cached.updated_at).getTime();
        if (age <= maxAgeMs) {
            const rows = Array.isArray(cached.payload) ? cached.payload : [];
            return rows.map((h) => ({ wallet: String(h.wallet), raw: BigInt(String(h.raw)) }));
        }
    }
    let rows = [];
    let lastError = null;
    for (const program of [TOKEN_PROGRAM, TOKEN_2022_PROGRAM]) {
        try {
            const part = await holderAccounts(program, mint);
            rows.push(...part);
            if (part.length)
                break;
        }
        catch (error) {
            lastError = error;
        }
    }
    if (!rows.length && lastError)
        throw lastError;
    const byOwner = new Map();
    for (const row of rows)
        byOwner.set(row.wallet, (byOwner.get(row.wallet) ?? 0n) + row.raw);
    rows = [...byOwner.entries()].map(([wallet, raw]) => ({ wallet, raw }));
    await db.from("api_cache").upsert({
        cache_key: cacheKey,
        payload: rows.map((h) => ({ wallet: h.wallet, raw: h.raw.toString() })),
        updated_at: new Date().toISOString(),
    });
    return rows;
}
export async function fetchDexScreenerToken(mint) {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${encodeURIComponent(mint)}`, {
        headers: { accept: "application/json" },
        signal: AbortSignal.timeout(10000),
        cache: "no-store",
    });
    if (!res.ok)
        throw new Error(`DexScreener failed: ${res.status}`);
    const json = await res.json();
    const pairs = Array.isArray(json?.pairs) ? json.pairs.filter((p) => p?.chainId === "solana") : [];
    const best = pairs.sort((a, b) => Number(b?.liquidity?.usd ?? 0) - Number(a?.liquidity?.usd ?? 0))[0] ?? null;
    return {
        priceUsd: Number(best?.priceUsd ?? 0),
        name: best?.baseToken?.name ?? null,
        symbol: best?.baseToken?.symbol ?? null,
        marketCap: Number(best?.marketCap ?? best?.fdv ?? 0),
        liquidityUsd: Number(best?.liquidity?.usd ?? 0),
        volume24h: Number(best?.volume?.h24 ?? 0),
    };
}
export async function fetchRecentSignatures(address, limit = 8) {
    return rpc("getSignaturesForAddress", [
        address,
        { limit, commitment: "confirmed" },
    ]);
}
export async function fetchParsedTransactionResult(signature) {
    try {
        return { transaction: await rpc('getTransaction', [signature, { commitment: 'confirmed', encoding: 'jsonParsed', maxSupportedTransactionVersion: 1 }]), failure: null };
    }
    catch (e) {
        return { transaction: null, failure: e instanceof SolanaRpcError ? e.kind : 'network', failureCode: e instanceof SolanaRpcError ? e.code : undefined };
    }
}
export async function fetchParsedTransaction(signature) { return (await fetchParsedTransactionResult(signature)).transaction; }
const SOL = "So11111111111111111111111111111111111111112";
async function getJson(url) {
    try {
        const r = await fetch(url, { cache: "no-store", signal: AbortSignal.timeout(12_000), headers: { accept: "application/json" } });
        if (!r.ok)
            return null;
        return await r.json();
    }
    catch {
        return null;
    }
}
export async function collectMarket(previousPayload, trackedMints = []) {
    const [profiles, boosts] = await Promise.all([
        getJson("https://api.dexscreener.com/token-profiles/latest/v1"),
        getJson("https://api.dexscreener.com/token-boosts/top/v1"),
    ]);
    const profileIcon = new Map();
    for (const p of profiles ?? []) {
        if (p.chainId !== "solana" || !p.tokenAddress)
            continue;
        const icon = p.icon || p.imageUrl;
        if (icon)
            profileIcon.set(p.tokenAddress, icon);
    }
    const boostMap = new Map();
    for (const b of boosts ?? []) {
        if (b.chainId !== "solana" || !b.tokenAddress)
            continue;
        boostMap.set(b.tokenAddress, Math.max(Number(b.totalAmount ?? b.amount ?? 0), boostMap.get(b.tokenAddress) ?? 0));
    }
    const addresses = [];
    const push = (a) => {
        if (!a || a === SOL || addresses.includes(a))
            return;
        addresses.push(a);
    };
    for (const b of boosts ?? [])
        if (b.chainId === "solana")
            push(b.tokenAddress);
    for (const p of profiles ?? [])
        if (p.chainId === "solana")
            push(p.tokenAddress);
    const tracked = (previousPayload?.tokens ?? []).map((t) => String(t.mint));
    const picked = [...new Set([...trackedMints.slice(0, 20), ...tracked.slice(0, 50), ...addresses, ...tracked])].slice(0, 100);
    const chunks = [];
    for (let i = 0; i < picked.length; i += 30)
        chunks.push(picked.slice(i, i + 30));
    const batch = await Promise.all(chunks.map((chunk) => getJson(`https://api.dexscreener.com/tokens/v1/solana/${chunk.join(",")}`)));
    const best = new Map();
    for (const pairs of batch) {
        for (const p of pairs ?? []) {
            if (p.chainId !== "solana" || !p.baseToken?.address)
                continue;
            const mint = p.baseToken.address;
            const prev = best.get(mint);
            if (!prev || Number(p.liquidity?.usd ?? 0) > Number(prev.liquidity?.usd ?? 0))
                best.set(mint, p);
        }
    }
    if (!best.size)
        throw new Error("Market sources unavailable; retaining last successful snapshot");
    const tokens = [...best.entries()].map(([mint, p]) => {
        const buys1h = Number(p.txns?.h1?.buys ?? 0);
        const sells1h = Number(p.txns?.h1?.sells ?? 0);
        return {
            mint,
            name: p.baseToken?.name ?? null,
            symbol: p.baseToken?.symbol ?? null,
            dex: p.dexId ?? null,
            pairAddress: p.pairAddress ?? null,
            quoteMint: p.quoteToken?.address ?? null,
            quoteSymbol: p.quoteToken?.symbol ?? null,
            priceUsd: Number(p.priceUsd ?? 0),
            marketCap: Number(p.marketCap ?? p.fdv ?? 0),
            fdv: p.fdv == null ? null : Number(p.fdv),
            liquidityUsd: Number(p.liquidity?.usd ?? 0),
            volume1h: Number(p.volume?.h1 ?? 0),
            volume24h: Number(p.volume?.h24 ?? 0),
            buys1h,
            sells1h,
            trades1h: buys1h + sells1h,
            priceChange1h: Number(p.priceChange?.h1 ?? 0),
            priceChange24h: Number(p.priceChange?.h24 ?? 0),
            boost: boostMap.get(mint) ?? 0,
            imageUrl: p.info?.imageUrl ?? profileIcon.get(mint) ?? null,
            hypeScore: 0,
            traffic: "flat",
            netFlowUsd1h: 0,
            activityDelta: 0,
            hypeDelta: 0,
            volumeDelta: 0,
        };
    })
        .filter((t) => t.marketCap > 0 || t.liquidityUsd > 0 || t.volume1h > 0)
        .sort((a, b) => (b.volume1h + b.trades1h * 30 + b.boost * 50) - (a.volume1h + a.trades1h * 30 + a.boost * 50))
        .slice(0, 100);
    for (const t of tokens) {
        // Fixed scales keep Hype comparable when the discovery universe changes.
        const tradeNorm = Math.min(1, Math.log10(t.trades1h + 1) / 4);
        const volumeNorm = Math.min(1, Math.log10(t.volume1h + 1) / 6);
        const boostNorm = Math.min(1, Math.log10(t.boost + 1) / 3);
        const buyRatio = t.trades1h ? t.buys1h / t.trades1h : 0;
        const momentumNorm = Math.max(0, Math.min(1, (t.priceChange1h + 12) / 36));
        t.hypeScore = Math.round((tradeNorm * .30 + buyRatio * .24 + momentumNorm * .22 + boostNorm * .14 + volumeNorm * .10) * 100);
        const imbalance = (t.buys1h - t.sells1h) / Math.max(1, t.trades1h);
        t.traffic = imbalance > .16 ? "in" : imbalance < -.16 ? "out" : "flat";
    }
    const previousTokens = new Map();
    for (const t of Array.isArray(previousPayload?.tokens) ? previousPayload.tokens : []) {
        if (t?.mint)
            previousTokens.set(String(t.mint), t);
    }
    const recentEvents = [];
    for (const t of tokens) {
        const prev = previousTokens.get(t.mint);
        if (!prev)
            continue;
        const deltaTrades = t.trades1h - Number(prev.trades1h ?? 0);
        const deltaVolume = t.volume1h - Number(prev.volume1h ?? 0);
        const previousHype = Number(prev.hypeScore ?? 0);
        t.activityDelta = deltaTrades;
        t.volumeDelta = deltaVolume;
        t.hypeDelta = t.hypeScore - previousHype;
        if (deltaTrades === 0 && Math.abs(deltaVolume) < 1 && t.hypeDelta === 0)
            continue;
        const kind = deltaTrades > 2 || t.hypeDelta >= 5 ? "surge" :
            deltaTrades < -2 || t.hypeDelta <= -5 ? "cooldown" :
                t.traffic === "in" ? "buy-pressure" : "sell-pressure";
        recentEvents.push({
            mint: t.mint,
            symbol: t.symbol,
            kind,
            deltaTrades,
            deltaVolume,
            hypeDelta: t.hypeDelta,
            at: new Date().toISOString(),
        });
    }
    recentEvents.sort((a, b) => (Math.abs(b.deltaTrades) * 100 + Math.abs(b.hypeDelta) * 10 + Math.abs(b.deltaVolume) / 1000) -
        (Math.abs(a.deltaTrades) * 100 + Math.abs(a.hypeDelta) * 10 + Math.abs(a.deltaVolume) / 1000));
    const shown = new Set(tokens.map((t) => t.mint));
    const core = new Set([
        SOL,
        "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        "Es9vMFrzaCERmJfrF4H2FYDgHkmPG8TbQnYQ8V4a8Qj",
    ]);
    const marketFlows = tokens.flatMap((t) => {
        if (!t.quoteMint || (!shown.has(t.quoteMint) && !core.has(t.quoteMint)))
            return [];
        const totalTrades = Math.max(1, t.buys1h + t.sells1h);
        const buyShare = t.buys1h / totalTrades;
        const sellShare = t.sells1h / totalTrades;
        const out = [];
        const buyUsd = t.volume1h * buyShare;
        const sellUsd = t.volume1h * sellShare;
        if (buyUsd > 1)
            out.push({
                from: t.quoteMint,
                to: t.mint,
                usd1h: buyUsd,
                trades1h: t.buys1h,
                kind: "buy",
                dex: t.dex,
                source: "market",
            });
        if (sellUsd > 1)
            out.push({
                from: t.mint,
                to: t.quoteMint,
                usd1h: sellUsd,
                trades1h: t.sells1h,
                kind: "sell",
                dex: t.dex,
                source: "market",
            });
        return out;
    });
    const byQuote = new Map();
    for (const t of tokens) {
        if (!t.quoteMint)
            continue;
        const list = byQuote.get(t.quoteMint) ?? [];
        list.push(t);
        byQuote.set(t.quoteMint, list);
    }
    const rotationFlows = [];
    for (const group of byQuote.values()) {
        const outTokens = group
            .filter((t) => t.sells1h > t.buys1h && t.volume1h > 100)
            .sort((a, b) => (b.sells1h - b.buys1h) - (a.sells1h - a.buys1h))
            .slice(0, 5);
        const inTokens = group
            .filter((t) => t.buys1h > t.sells1h && t.volume1h > 100)
            .sort((a, b) => (b.buys1h - b.sells1h) - (a.buys1h - a.sells1h))
            .slice(0, 5);
        for (const from of outTokens) {
            const sellShare = from.sells1h / Math.max(1, from.trades1h);
            const sellUsd = from.volume1h * sellShare;
            for (const to of inTokens) {
                if (from.mint === to.mint)
                    continue;
                const buyShare = to.buys1h / Math.max(1, to.trades1h);
                const buyUsd = to.volume1h * buyShare;
                const usd1h = Math.min(sellUsd, buyUsd) * 0.30;
                if (usd1h < 150)
                    continue;
                const confidence = Math.min(0.82, 0.42 + Math.min(sellShare, buyShare) * 0.36);
                rotationFlows.push({
                    from: from.mint,
                    to: to.mint,
                    usd1h,
                    trades1h: Math.min(from.sells1h, to.buys1h),
                    kind: "rotation",
                    dex: to.dex,
                    source: "inferred",
                    confidence,
                });
            }
        }
    }
    const flows = [...marketFlows, ...rotationFlows]
        .sort((a, b) => (b.usd1h * ("confidence" in b ? Number(b.confidence ?? 1) : 1)) - (a.usd1h * ("confidence" in a ? Number(a.confidence ?? 1) : 1)))
        .slice(0, 220);
    const netFlow = new Map();
    for (const flow of flows) {
        if (!shown.has(flow.from) || !shown.has(flow.to))
            continue;
        netFlow.set(flow.from, (netFlow.get(flow.from) ?? 0) - flow.usd1h);
        netFlow.set(flow.to, (netFlow.get(flow.to) ?? 0) + flow.usd1h);
    }
    for (const token of tokens)
        token.netFlowUsd1h = netFlow.get(token.mint) ?? 0;
    const hotPath = [...rotationFlows]
        .sort((a, b) => (b.usd1h * b.confidence) - (a.usd1h * a.confidence))
        .slice(0, 6)
        .map((f) => ({
        from: f.from,
        to: f.to,
        score: Math.round(f.usd1h * f.confidence),
        confidence: f.confidence,
    }));
    const observedTrades1h = tokens.reduce((sum, t) => sum + t.trades1h, 0);
    const payload = {
        fetchedAt: new Date().toISOString(),
        tokens,
        flows,
        hotPath,
        recentEvents: recentEvents.slice(0, 12),
        network: {
            swaps1h: observedTrades1h,
            source: "dexscreener",
        },
        live: true,
    };
    return payload;
}
const finite = (n) => typeof n === 'number' && Number.isFinite(n);
export const percentChange = (value, previous) => previous > 0 ? (value - previous) / previous * 100 : null;
export function deriveSignals(t, previous, at, baselineAt) {
    const minutes = baselineAt ? (Date.parse(at) - Date.parse(baselineAt)) / 60_000 : 0;
    const comparable = previous && minutes > 0 && minutes <= 60 && previous.pairAddress === t.pairAddress;
    const hypeDelta = comparable ? (t.hypeScore ?? 0) - (previous.hypeScore ?? 0) : null;
    const volumeDelta = comparable ? (t.volume1h ?? 0) - (previous.volume1h ?? 0) : null;
    const volumeVelocity = volumeDelta == null ? null : volumeDelta / minutes;
    const liquidityChange = comparable ? (t.liquidityUsd ?? 0) - (previous.liquidityUsd ?? 0) : null;
    const liquidityChangePct = comparable ? percentChange(t.liquidityUsd ?? 0, previous.liquidityUsd ?? 0) : null;
    const trades = (t.buys1h ?? 0) + (t.sells1h ?? 0);
    const liquidityWarning = liquidityChangePct != null && liquidityChangePct <= -25 && (previous?.liquidityUsd ?? 0) >= 5000;
    const riskFactors = [];
    const factor = (label, points, value) => riskFactors.push({ label, points: Math.round(points), value });
    if ((t.liquidityUsd ?? 0) < 10000)
        factor('Low liquidity (< $10k)', 20, t.liquidityUsd ?? 0);
    if (liquidityWarning)
        factor('Liquidity dropped ≥25%', 25, liquidityChangePct);
    if (finite(t.top10SupplyPct) && t.top10SupplyPct > 40)
        factor('Top 10 concentration (pool/program owners included)', Math.min(20, (t.top10SupplyPct - 40) * .4), t.top10SupplyPct);
    if (finite(t.largestHolderPct) && t.largestHolderPct > 10)
        factor('Large holder dominance', Math.min(20, (t.largestHolderPct - 10)), t.largestHolderPct);
    if (finite(t.linkedSupplyPct) && t.linkedSupplyPct > 10)
        factor('Linked-wallet supply concentration', Math.min(15, (t.linkedSupplyPct - 10) * .5), t.linkedSupplyPct);
    else if (finite(t.suspiciousWallets) && t.suspiciousWallets > 0)
        factor('Wallet relationship evidence', Math.min(10, t.suspiciousWallets * 2), t.suspiciousWallets);
    if (trades > 20 && (t.buys1h ?? 0) / trades < .3)
        factor('Strong sell pressure', 15, (t.sells1h ?? 0) / trades * 100);
    const fdvLiquidityRatio = finite(t.fdv) && t.fdv > 0 && (t.liquidityUsd ?? 0) > 0 ? t.fdv / (t.liquidityUsd) : null;
    if (fdvLiquidityRatio != null && fdvLiquidityRatio > 100)
        factor('FDV / liquidity imbalance', Math.min(15, Math.log10(fdvLiquidityRatio / 100) * 15 + 5), fdvLiquidityRatio);
    const risk = riskFactors.reduce((n, f) => n + f.points, 0);
    const reasons = riskFactors.map(f => f.label);
    const hypeVelocity = hypeDelta == null ? null : hypeDelta / minutes;
    const hypeAcceleration = hypeVelocity != null && finite(previous?.hypeVelocity) ? (hypeVelocity - previous.hypeVelocity) / minutes : null;
    const acceleration = volumeVelocity != null && finite(previous?.volumeVelocity) ? (volumeVelocity - previous.volumeVelocity) / minutes : null;
    const sample = t.trafficSample, sampleAge = sample ? (Date.parse(at) - Date.parse(sample.observedAt)) / 60000 : null, sample15 = sample?.windows?.['15'];
    const observedSample = sample && sample15 && sampleAge != null && sampleAge >= -1 && sampleAge < 10 && sample15.swaps >= 5;
    return { hypeDelta, hypeVelocity, hypeAcceleration, fdvLiquidityRatio, riskFactors,
        volumeDelta, volumeVelocity, volumeAcceleration: acceleration, liquidityChange, liquidityChangePct,
        buyPressure: trades ? (t.buys1h ?? 0) / trades * 100 : null,
        liquidityWarning, baselineAt: comparable ? baselineAt : null,
        riskScore: Math.round(Math.min(100, risk)), riskReasons: reasons,
        trafficEvidence: sample?.evidence ?? null, trafficObservedAt: sample?.observedAt ?? null,
        observedBuyPressure15m: observedSample ? sample15.buys / sample15.swaps * 100 : null,
        observedNetFlowUsd15m: observedSample ? sample15.netUsd : null,
        riskCoverage: finite(t.top10SupplyPct) ? 'market + observed holders (heuristic)' : 'market only; holder risk unknown' };
}
export function evaluateAlerts(t, previous, at) {
    const alerts = [];
    const add = (kind, value, message, severity = 'info') => alerts.push({
        id: `${t.mint}:${kind}:${at}`, mint: t.mint, symbol: t.symbol ?? null, kind, severity, value, message, at,
        deltaTrades: 0, deltaVolume: t.volumeDelta ?? 0, hypeDelta: t.hypeDelta ?? 0
    });
    if ((t.hypeScore ?? 0) >= 70 && (previous?.hypeScore ?? 0) < 70)
        add('hype-threshold', t.hypeScore, 'Hype crossed 70/100');
    if ((t.hypeVelocity ?? 0) >= 3 && (previous?.hypeVelocity ?? 0) < 3)
        add('hype-velocity', t.hypeVelocity, 'Hype rises ≥3 points/min');
    if ((t.hypeAcceleration ?? 0) >= .3 && (previous?.hypeAcceleration ?? 0) < .3)
        add('hype-acceleration', t.hypeAcceleration, 'Hype velocity accelerates ≥0.3 points/min²');
    if ((t.hypeDelta ?? 0) >= 5 && (previous?.hypeDelta ?? 0) < 5)
        add('hype', t.hypeDelta, 'Hype increased ≥5 points');
    const holderGrowth = t.holderWindows?.['5']?.holderGrowthPct;
    const holderMinutes = t.holderBaselineAt && t.holderObservedAt ? (Date.parse(t.holderObservedAt) - Date.parse(t.holderBaselineAt)) / 60000 : null;
    const fastHolders = holderGrowth ?? (holderMinutes != null && holderMinutes <= 8 ? t.holderGrowthPct : null);
    if ((fastHolders ?? 0) >= 5 && t.holderObservedAt !== previous?.holderObservedAt)
        add('holder-growth', fastHolders, 'Observed holders grew ≥5% over roughly 5m');
    const trades = (t.buys1h ?? 0) + (t.sells1h ?? 0), observed = finite(t.observedBuyPressure15m), pressure = observed ? t.observedBuyPressure15m : (trades >= 20 ? t.buyPressure : null);
    const previousPressure = observed ? previous?.observedBuyPressure15m : previous?.buyPressure;
    if (finite(pressure) && pressure >= 70 && (previousPressure ?? 0) < 70)
        add('buy-pressure', pressure, observed ? 'Observed swap sample buy share crossed 70%' : 'Aggregated buy count share crossed 70%');
    if (t.liquidityWarning && !previous?.liquidityWarning)
        add('liquidity-disappearing', t.liquidityChangePct, 'Liquidity dropped ≥25%', 'critical');
    else if (finite(t.liquidityChangePct) && t.liquidityChangePct >= 20 && (previous?.liquidityChangePct ?? 0) < 20)
        add('liquidity', t.liquidityChangePct, 'Liquidity increased ≥20%');
    if (t.holderObservedAt !== previous?.holderObservedAt) {
        if ((t.whaleEnter ?? 0) > 0)
            add('whale-enter', t.whaleEnter, 'Owners crossed into ≥1% supply positions (includes program owners)');
        if ((t.whaleExit ?? 0) > 0)
            add('whale-exit', t.whaleExit, 'Owners left ≥1% supply positions', 'warning');
    }
    if (t.holderObservedAt !== previous?.holderObservedAt)
        for (const sale of t.topHolderSales ?? []) {
            if ((previous?.topHolderSales ?? []).some(p => p.signature === sale.signature && p.wallet === sale.wallet))
                continue;
            add('top-holder-selling', sale.amount, `Top owner ${sale.wallet.slice(0, 6)} has swap-like outflow; inspect ${sale.signature}`, 'warning');
            alerts.at(-1).id = `${t.mint}:top-holder-selling:${sale.wallet}:${sale.signature}`;
        }
    return alerts;
}
export function suppressRepeatedAlerts(candidates, history, cooldownMinutes = 30) {
    const ids = new Set(history.map(a => a.id)), latest = new Map();
    for (const a of history) {
        const key = `${a.mint}:${a.kind}`, time = Date.parse(a.at);
        if (Number.isFinite(time) && time > (latest.get(key) ?? -Infinity))
            latest.set(key, time);
    }
    return candidates.filter(a => { if (ids.has(a.id))
        return false; const prior = latest.get(`${a.mint}:${a.kind}`), time = Date.parse(a.at); return prior == null || !Number.isFinite(time) || time - prior >= cooldownMinutes * 60000; });
}
export function collapseAlertHistory(alerts) { const seen = new Set(); return alerts.filter(a => { const key = `${a.mint}:${a.kind}`; return !seen.has(key) && !!seen.add(key); }); }
export function prioritizeAlerts(alerts, limit = 8) {
    const severity = { critical: 3, warning: 2, info: 1 }, rank = (a) => severity[a.severity] * 1e9 + Math.abs(a.value || 0);
    const strongest = new Map();
    for (const alert of alerts) {
        const current = strongest.get(alert.mint);
        if (!current || rank(alert) > rank(current))
            strongest.set(alert.mint, alert);
    }
    return [...strongest.values()].sort((a, b) => rank(b) - rank(a)).slice(0, limit);
}
export const moverCategories = [
    { key: 'hypeVelocity', label: 'Hype Movers', unit: 'H/min' },
    { key: 'holderGrowthPct', label: 'Holder Movers', unit: '%' },
    { key: 'volumeAcceleration', label: 'Volume Movers', unit: '$/min²' },
    { key: 'liquidityChangePct', label: 'Liquidity Movers', unit: '%' },
    { key: 'smartMoneyFlowUsd', label: 'Smart Money Movers', unit: '$ observed whale balance Δ' },
];
export function rankMovers(tokens, key) {
    return tokens.filter(t => finite(t[key])).sort((a, b) => Math.abs(b[key]) - Math.abs(a[key]));
}
export function compareMarketWindows(token, at, baselines) {
    const windows = {};
    for (const b of baselines) {
        if (b.mint !== token.mint || b.payload.pairAddress !== token.pairAddress)
            continue;
        windows[String(b.window_minutes)] = { baselineAt: b.observed_at, observedAt: at, elapsedMinutes: (Date.parse(at) - Date.parse(b.observed_at)) / 60000,
            hypeDelta: (token.hypeScore ?? 0) - (b.payload.hypeScore ?? 0),
            volumeChangePct: percentChange(token.volume1h ?? 0, b.payload.volume1h ?? 0),
            liquidityChangePct: percentChange(token.liquidityUsd ?? 0, b.payload.liquidityUsd ?? 0),
            priceChangePct: percentChange(token.priceUsd ?? 0, b.payload.priceUsd ?? 0) };
    }
    return windows;
}
const QUOTES = new Set(['So11111111111111111111111111111111111111112', 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v', 'Es9vMFrzaCERmJfrF4H2FYDgHkmPG8TbQnYQ8V4a8Qj']);
/** Swap-like evidence only: a token transfer alone must never be labelled selling. */
export function detectSwapLikeSale(tx, mint, wallet, since) {
    if (!tx || tx.meta?.err || !tx.blockTime || tx.blockTime * 1000 <= Date.parse(since))
        return null;
    const delta = new Map();
    for (const [key, sign] of [['preTokenBalances', -1], ['postTokenBalances', 1]])
        for (const row of tx.meta?.[key] ?? []) {
            if (row.owner !== wallet)
                continue;
            const amount = Number(row.uiTokenAmount?.uiAmountString ?? row.uiTokenAmount?.uiAmount ?? 0);
            delta.set(row.mint, (delta.get(row.mint) ?? 0) + sign * amount);
        }
    const loss = -(delta.get(mint) ?? 0);
    if (loss <= 0 || ![...delta].some(([quote, amount]) => quote !== mint && QUOTES.has(quote) && amount > 0))
        return null;
    const signature = tx.transaction?.signatures?.[0];
    if (!signature)
        return null;
    return { wallet, signature: String(signature), amount: loss, at: new Date(tx.blockTime * 1000).toISOString() };
}
// Bounded sample, never a claim that every holder has been analyzed.
export async function sampleWalletRelationships(balances, mint, since, previousLargest) {
    const sample = [...balances].sort((a, b) => b.balance - a.balance).slice(0, 4);
    if (previousLargest && !sample.some(h => h.wallet === previousLargest))
        sample[sample.length - 1] = { wallet: previousLargest, balance: 0 };
    const sales = [];
    const funders = new Map();
    const signatures = new Map();
    let analyzed = 0;
    await Promise.all(sample.map(async (h) => {
        const recent = await fetchRecentSignatures(h.wallet, 2).catch(() => null);
        if (!recent)
            return;
        const txs = await Promise.all(recent.filter(s => !s.err).map(s => fetchParsedTransaction(s.signature)));
        if (!txs.some(Boolean))
            return;
        analyzed++;
        for (const tx of txs) {
            if (mint && since) {
                const sale = detectSwapLikeSale(tx, mint, h.wallet, since);
                if (sale)
                    sales.push(sale);
            }
            const instructions = [...(tx?.transaction?.message?.instructions ?? []), ...(tx?.meta?.innerInstructions ?? []).flatMap((x) => x.instructions ?? [])];
            for (const ix of instructions) {
                if (ix?.program !== 'system' || ix.parsed?.type !== 'transfer')
                    continue;
                const info = ix.parsed.info;
                if (info?.destination !== h.wallet || !info.source || info.source === h.wallet)
                    continue;
                const group = funders.get(info.source) ?? new Set();
                group.add(h.wallet);
                funders.set(info.source, group);
                const sigs = signatures.get(info.source) ?? new Set();
                sigs.add(String(tx.transaction.signatures?.[0] ?? ''));
                signatures.set(info.source, sigs);
            }
        }
    }));
    const wallets = new Set(balances.map(h => h.wallet));
    const evidence = [];
    for (const [funder, group] of funders) {
        if (group.size >= 2)
            evidence.push({ wallets: [...group], kind: 'common-funder', evidence: [`funder:${funder}`, ...(signatures.get(funder) ?? [])] });
        else if (wallets.has(funder))
            evidence.push({ wallets: [funder, ...group], kind: 'direct-funder', evidence: [...(signatures.get(funder) ?? [])] });
    }
    return { analyzed, sampled: sample.length, evidence, sales };
}
// One adapter boundary: replace this to use any indexer or RPC provider.
export const rpcHolderProvider = {
    async observe(mint) {
        const [{ supply, decimals }, holders] = await Promise.all([fetchPublicSupply(mint), fetchPublicHolders(mint, 0)]);
        if (!supply || !holders.length)
            throw new Error('Incomplete holder observation');
        return { supply, decimals, balances: holders.map(h => ({ wallet: h.wallet, balance: Number(h.raw) / 10 ** decimals })) };
    }
};
export async function observeHolders(mint, price, provider = rpcHolderProvider) {
    const db = admin();
    const key = `intelligence:holders:${mint}`;
    const { data: prev, error: readError } = await db.from('api_cache').select('payload,updated_at').eq('cache_key', key).maybeSingle();
    if (readError)
        throw readError;
    const current = await provider.observe(mint);
    const at = new Date().toISOString();
    const before = prev?.payload;
    const previous = before ? new Map(before.balances.map(h => [h.wallet, h.balance])) : null;
    const previousWhales = before ? new Set(before.balances.filter(h => h.balance / before.supply >= .01).map(h => h.wallet)) : null;
    const whales = new Set(current.balances.filter(h => h.balance / current.supply >= .01).map(h => h.wallet));
    const wallets = new Set(current.balances.map(h => h.wallet));
    const { data: links, error: linkError } = await db.from('wallet_links').select('wallet_a,wallet_b,kind,signal_count').eq('token_mint', mint);
    const linked = new Set(), suspicious = new Set();
    for (const link of links ?? []) {
        if (!wallets.has(link.wallet_a) || !wallets.has(link.wallet_b))
            continue;
        linked.add(link.wallet_a);
        linked.add(link.wallet_b);
        if (link.kind === 'funder' || link.signal_count >= 3) {
            suspicious.add(link.wallet_a);
            suspicious.add(link.wallet_b);
        }
    }
    const previousLargest = before ? [...before.balances].sort((a, b) => b.balance - a.balance)[0]?.wallet : undefined;
    const relationSample = await sampleWalletRelationships(current.balances, mint, prev?.updated_at, previousLargest);
    for (const group of relationSample.evidence)
        for (const wallet of group.wallets) {
            linked.add(wallet);
            suspicious.add(wallet);
        }
    const relationshipKnown = !!links?.length || relationSample.analyzed > 0;
    const whaleWallets = new Set([...whales, ...(previousWhales ?? [])]);
    const balanceNow = new Map(current.balances.map(h => [h.wallet, h.balance]));
    const sorted = [...current.balances].sort((a, b) => b.balance - a.balance);
    const { data: holderWindows, error: windowError } = await db.rpc('holder_window_comparisons', { p_mint: mint, p_at: at, p_wallets: [...wallets] });
    if (windowError)
        throw windowError;
    const metrics = {
        holderCount: current.balances.length,
        holderGrowth: previous ? current.balances.length - previous.size : null,
        holderGrowthPct: previous?.size ? (current.balances.length - previous.size) / previous.size * 100 : null,
        newHolders: previous ? current.balances.filter(h => !previous.has(h.wallet)).length : null,
        exitedHolders: previous ? [...previous.keys()].filter(w => !wallets.has(w)).length : null,
        largestHolderPct: sorted.length ? sorted[0].balance / current.supply * 100 : null,
        whaleConcentrationPct: current.balances.filter(h => whales.has(h.wallet)).reduce((n, h) => n + h.balance, 0) / current.supply * 100,
        linkedSupplyPct: relationshipKnown ? current.balances.filter(h => linked.has(h.wallet)).reduce((n, h) => n + h.balance, 0) / current.supply * 100 : null,
        holderWindows: holderWindows ?? {},
        topHolderSales: relationSample.sales,
        freshWallets: previous ? current.balances.filter(h => !previous.has(h.wallet)).length : null,
        top10SupplyPct: Math.min(100, [...current.balances].sort((a, b) => b.balance - a.balance).slice(0, 10).reduce((n, h) => n + h.balance, 0) / current.supply * 100),
        linkedWallets: !relationshipKnown ? null : linked.size,
        suspiciousWallets: !relationshipKnown ? null : suspicious.size,
        whaleEnter: previousWhales ? [...whales].filter(w => !previousWhales.has(w)).length : null,
        whaleExit: previousWhales ? [...previousWhales].filter(w => !whales.has(w)).length : null,
        smartMoneyFlowUsd: previous ? [...whaleWallets].reduce((n, w) => n + ((balanceNow.get(w) ?? 0) - (previous.get(w) ?? 0)) * price, 0) : null,
        relationshipCoverage: `${relationSample.analyzed}/${relationSample.sampled} largest owners sampled; stored links ${linkError ? 'unavailable' : links?.length ?? 0}. Recent transactions only.`,
        walletEvidence: relationSample.evidence,
        holderObservedAt: at, holderBaselineAt: previous ? prev.updated_at : null,
    };
    const { error } = await db.rpc('save_holder_observation', { p_mint: mint, p_at: at, p_payload: { ...current, price, metrics }, p_wallets: [...wallets] });
    if (error)
        throw error;
    return metrics;
}
// Verified against official PumpSwap IDL and Raydium cp-swap Swap accounts.
// https://github.com/pump-fun/pump-public-docs/blob/main/idl/pump_amm.json
// https://github.com/raydium-io/raydium-cp-swap/tree/master/programs/cp-swap/src/instructions
export const swapPrograms = [
    {
        "program": "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
        "name": "PumpSwap",
        "poolIndex": 0,
        "userIndex": 1,
        "userTokenIndices": [
            5,
            6
        ],
        "vaultIndices": [
            7,
            8
        ],
        "discriminators": [
            [
                102,
                6,
                61,
                18,
                1,
                218,
                235,
                234
            ],
            [
                198,
                46,
                21,
                82,
                180,
                217,
                232,
                112
            ],
            [
                51,
                230,
                133,
                164,
                1,
                127,
                131,
                173
            ]
        ]
    },
    {
        "program": "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C",
        "name": "Raydium CPMM",
        "poolIndex": 3,
        "userIndex": 0,
        "userTokenIndices": [
            4,
            5
        ],
        "vaultIndices": [
            6,
            7
        ],
        "discriminators": [
            [
                143,
                190,
                90,
                218,
                196,
                30,
                51,
                222
            ],
            [
                55,
                217,
                98,
                86,
                163,
                74,
                180,
                173
            ]
        ]
    }
];
export const WSOL_MINT = 'So11111111111111111111111111111111111111112';
export const USDC_MINT = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const safePrograms = new Set(['11111111111111111111111111111111', 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA', 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb', 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL', 'ComputeBudget111111111111111111111111111111', 'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr']);
function decodeInstructionBytes(value) { const alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'; let n = 0n; for (const c of value) {
    const i = alphabet.indexOf(c);
    if (i < 0)
        return [];
    n = n * 58n + BigInt(i);
} const bytes = []; while (n) {
    bytes.unshift(Number(n & 255n));
    n >>= 8n;
} for (const c of value) {
    if (c !== '1')
        break;
    bytes.unshift(0);
} return bytes; }
/** Conservative direct single-swap decoder. Routers, liquidity operations and ambiguous balance movements stay unrecognized. */
export function decodeDirectSwap(tx, mint, pool, solUsd) {
    if (!tx || !tx.meta || tx.meta.err || !tx.blockTime || !tx.transaction?.signatures?.[0])
        return null;
    if (tx.version != null && tx.version !== 'legacy' && tx.version !== 0 && tx.version !== 1)
        return null;
    if (!Array.isArray(tx.transaction.message?.accountKeys) || !Array.isArray(tx.transaction.message?.instructions))
        return null;
    const keys = tx.transaction.message?.accountKeys ?? [];
    const addresses = keys.map((k) => typeof k === 'string' ? k : k.pubkey);
    const instructions = tx.transaction.message?.instructions ?? [];
    const candidates = instructions.filter((i) => swapPrograms.some(p => p.program === (i.programId ?? addresses[i.programIdIndex])));
    if (candidates.length !== 1)
        return null;
    const ix = candidates[0], program = ix.programId ?? addresses[ix.programIdIndex], adapter = swapPrograms.find(p => p.program === program);
    // Reject extra program calls, including routing/multiple DEX legs.
    if (instructions.some((i) => { const id = i.programId ?? addresses[i.programIdIndex]; return id !== program && !safePrograms.has(id); }))
        return null;
    // Top-level token transfers could contaminate net account deltas.
    if (instructions.some((i) => { const id = i.programId ?? addresses[i.programIdIndex]; if (id !== 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' && id !== 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb')
        return false; return i.parsed?.type?.startsWith('transfer') || (typeof i.data === 'string' && [3, 12].includes(decodeInstructionBytes(i.data)[0])); }))
        return null;
    if (typeof ix.data !== 'string')
        return null;
    const bytes = decodeInstructionBytes(ix.data);
    if (bytes.length < 24)
        return null;
    if (!adapter.discriminators.some(d => d.every((b, i) => bytes[i] === b)))
        return null;
    const accounts = (ix.accounts ?? []).map((a) => typeof a === 'number' ? addresses[a] : a);
    if (accounts[adapter.poolIndex] !== pool)
        return null;
    const wallet = accounts[adapter.userIndex], walletKey = keys.find((k) => k.pubkey === wallet);
    if (!wallet || !walletKey?.signer)
        return null;
    const balances = new Map();
    for (const [field, sign] of [['preTokenBalances', -1], ['postTokenBalances', 1]])
        for (const b of tx.meta[field] ?? []) {
            const amount = Number(b.uiTokenAmount?.uiAmountString ?? b.uiTokenAmount?.uiAmount);
            if (!Number.isFinite(amount))
                return null;
            const before = balances.get(b.accountIndex);
            if (before && before.mint !== b.mint)
                return null;
            balances.set(b.accountIndex, { mint: b.mint, owner: b.owner ?? before?.owner, delta: (before?.delta ?? 0) + sign * amount });
        }
    const user = adapter.userTokenIndices.map(i => balances.get(addresses.indexOf(accounts[i])));
    const target = user.find(b => b?.mint === mint && b.owner === wallet);
    if (!target || !target.delta)
        return null;
    const vaults = adapter.vaultIndices.map(i => balances.get(addresses.indexOf(accounts[i])));
    const targetVault = vaults.find(b => b?.mint === mint), quote = vaults.find(b => b && b.mint !== mint && (b.mint === WSOL_MINT || b.mint === USDC_MINT));
    if (!targetVault || !quote || !quote.delta || Math.sign(target.delta) === Math.sign(targetVault.delta) || Math.sign(target.delta) !== Math.sign(quote.delta))
        return null;
    const quoteAmount = Math.abs(quote.delta), price = quote.mint === USDC_MINT ? 1 : solUsd;
    return { pool, signature: tx.transaction.signatures[0], wallet, side: target.delta > 0 ? 'buy' : 'sell', token_amount: Math.abs(target.delta), quote_mint: quote.mint, quote_amount: quoteAmount, usd_value: price != null && price > 0 ? quoteAmount * price : null, block_at: new Date(tx.blockTime * 1000).toISOString(), program: adapter.name };
}
export function summarizeTraffic(rows, scans, at, pool, context, rowLimitReached = false) {
    const now = Date.parse(at), sorted = [...rows].filter(s => s.pool === pool && Date.parse(s.block_at) <= now).sort((a, b) => Date.parse(a.block_at) - Date.parse(b.block_at));
    const windows = {};
    for (const minutes of [5, 15, 60]) {
        const cutoff = now - minutes * 60000, sample = sorted.filter(s => Date.parse(s.block_at) >= cutoff), buy = sample.filter(s => s.side === 'buy'), sell = sample.filter(s => s.side === 'sell');
        const buyers = new Set(buy.map(s => s.wallet)), sellers = new Set(sell.map(s => s.wallet));
        const earlier = new Set(sorted.filter(s => Date.parse(s.block_at) < cutoff && s.side === 'buy').map(s => s.wallet));
        const quick = new Set();
        for (const b of buy)
            if (sample.some(s => s.wallet === b.wallet && s.side === 'sell' && Date.parse(s.block_at) > Date.parse(b.block_at) && Date.parse(s.block_at) - Date.parse(b.block_at) <= 15 * 60000))
                quick.add(b.wallet);
        const allPriced = sample.length > 0 && sample.every(s => s.usd_value != null && Number.isFinite(s.usd_value));
        const amount = (r) => allPriced ? r.reduce((n, s) => n + (s.usd_value ?? 0), 0) : null;
        const buyUsd = amount(buy), sellUsd = amount(sell), sizes = buy.filter(s => s.usd_value != null).map(s => s.usd_value).sort((a, b) => a - b);
        const spend = new Map();
        for (const b of buy)
            spend.set(b.wallet, (spend.get(b.wallet) ?? 0) + (b.usd_value ?? 0));
        const holderTime = context?.holderAt ? Date.parse(context.holderAt) : NaN, holderFresh = Number.isFinite(holderTime) && now - holderTime >= 0 && now - holderTime < 60 * 60000 && context?.wallets;
        const assessed = holderFresh ? [...buyers].filter(w => buy.filter(s => s.wallet === w).every(s => Date.parse(s.block_at) <= holderTime)) : [];
        windows[minutes] = { minutes, swaps: sample.length, buys: buy.length, sells: sell.length, buyers: buyers.size, sellers: sellers.size, newSampleBuyers: [...buyers].filter(w => !earlier.has(w)).length, repeatSampleBuyers: [...buyers].filter(w => earlier.has(w)).length, quickResellers: quick.size, buyUsd, sellUsd, netUsd: buyUsd != null && sellUsd != null ? buyUsd - sellUsd : null, medianBuyUsd: sizes.length ? (sizes[Math.floor((sizes.length - 1) / 2)] + sizes[Math.floor(sizes.length / 2)]) / 2 : null, largestBuyUsd: sizes.length ? sizes.at(-1) : null, top3BuyerSharePct: buyUsd != null && buyUsd > 0 ? [...spend.values()].sort((a, b) => b - a).slice(0, 3).reduce((n, v) => n + v, 0) / buyUsd * 100 : null, retainedBuyers: assessed.length ? assessed.filter(w => context?.wallets?.has(w)).length : null, retentionChecked: assessed.length, linkedBuyers: context?.linkedWallets ? [...buyers].filter(w => context.linkedWallets.has(w)).length : null, firstSwapAt: sample[0]?.block_at ?? null, lastSwapAt: sample.at(-1)?.block_at ?? null };
    }
    const failures = scans.reduce((acc, s) => { for (const [k, v] of Object.entries(s.failures ?? {}))
        acc[k] = (acc[k] ?? 0) + Number(v); return acc; }, {}), parsed = scans.reduce((n, s) => n + (s.parsed ?? 0), 0), recognized = scans.reduce((n, s) => n + (s.recognized ?? 0), 0), unavailable = scans.reduce((n, s) => n + (s.unavailable ?? 0), 0);
    const evidence = unavailable > 0 || Object.values(failures).some(v => v > 0) ? 'degraded' : recognized >= 5 ? 'usable' : parsed >= 5 ? 'sparse' : 'warming';
    return { observedAt: at, pool, coverage: 'partial', evidence, failures, scans: scans.length, listedSignatures: scans.reduce((n, s) => n + (s.listed ?? 0), 0), parsedTransactions: parsed, recognizedTransactions: recognized, unavailableTransactions: unavailable, unrecognizedTransactions: scans.reduce((n, s) => n + (s.unrecognized ?? 0), 0), limitedScans: scans.filter(s => s.limited).length, rowLimitReached, windows, note: 'Partial sample of one selected pool; direct PumpSwap / Raydium CPMM only. Pool-vault quote movement excludes some fees. USD uses USDC=$1 or SOL price at scan time, not historical execution USD. New buyers means first seen in retained 2h sample; quick resale does not establish profit. No completeness or bot verdict.' };
}
export async function observeTraffic(token, solUsd, holder, deadline = Date.now() + 45000) {
    if (!token.pairAddress)
        throw new Error('No selected pool');
    const db = admin(), at = new Date().toISOString();
    const recent = await fetchRecentSignatures(token.pairAddress, 12);
    const since = new Date(Date.now() - 2 * 3600000).toISOString();
    const prior = await db.from('traffic_swaps').select('mint,pool,signature,wallet,side,token_amount,quote_mint,quote_amount,usd_value,block_at,program').eq('mint', token.mint).gte('block_at', since).order('block_at', { ascending: false }).limit(1000);
    if (prior.error)
        throw prior.error;
    const scans = await db.from('traffic_scans').select('payload').eq('mint', token.mint).gte('scanned_at', since).order('scanned_at', { ascending: false }).limit(100);
    if (scans.error)
        throw scans.error;
    const seen = new Set((scans.data ?? []).flatMap(s => s.payload.processedSignatures ?? []));
    const pending = (scans.data ?? []).filter(s => s.payload.pool === token.pairAddress).flatMap(s => s.payload.pendingSignatures ?? []);
    const eligible = [...new Map([...pending, ...recent].filter(s => !s.err && s.blockTime && s.blockTime * 1000 >= Date.now() - 3600000 && s.blockTime * 1000 <= Date.now() - 10000 && !seen.has(s.signature)).map(s => [s.signature, s])).values()].sort((a, b) => a.blockTime - b.blockTime).slice(0, 12);
    const swaps = [];
    const processed = [];
    let parsed = 0, unavailable = 0, unrecognized = 0;
    const failures = {};
    const retry = [];
    let attempted = 0;
    for (const s of eligible) {
        if (Date.now() >= deadline - 16000)
            break;
        attempted++;
        const result = await fetchParsedTransactionResult(s.signature);
        if (!result.transaction) {
            unavailable++;
            const reason = result.failure ?? 'not_found';
            const key = result.failureCode != null ? `${reason}:${result.failureCode}` : reason;
            failures[key] = (failures[key] ?? 0) + 1;
            retry.push({ signature: s.signature, blockTime: s.blockTime });
            if (['rate_limited', 'forbidden', 'timeout', 'rpc_error'].includes(reason))
                break;
            continue;
        }
        parsed++;
        processed.push(s.signature);
        const swap = decodeDirectSwap(result.transaction, token.mint, token.pairAddress, solUsd);
        if (swap)
            swaps.push(swap);
        else
            unrecognized++;
    }
    const deferred = recent.filter(s => !s.err && s.blockTime && s.blockTime * 1000 > Date.now() - 10000 && !seen.has(s.signature)).map(s => ({ signature: s.signature, blockTime: s.blockTime }));
    const unattempted = eligible.slice(attempted).map(s => ({ signature: s.signature, blockTime: s.blockTime }));
    const scan = { pool: token.pairAddress, listed: recent.length, parsed, recognized: swaps.length, unavailable, unrecognized, failures, limited: recent.length === 12 || attempted < eligible.length, processedSignatures: processed, pendingSignatures: [...new Map([...retry, ...unattempted, ...deferred].map(s => [s.signature, s])).values()].slice(0, 12), oldestListedAt: recent.at(-1)?.blockTime ? new Date(recent.at(-1).blockTime * 1000).toISOString() : null };
    const save = await db.rpc('save_traffic_sample', { p_mint: token.mint, p_at: at, p_swaps: swaps, p_scan: scan });
    if (save.error)
        throw save.error;
    const merged = new Map();
    for (const row of [...(prior.data ?? []), ...swaps])
        merged.set(`${row.signature}:${row.wallet}`, row);
    const cache = await db.from('api_cache').select('payload,updated_at').eq('cache_key', `intelligence:holders:${token.mint}`).maybeSingle();
    const linked = holder?.linkedWallets != null && holder?.walletEvidence ? new Set(holder.walletEvidence.flatMap(e => e.wallets)) : undefined;
    const summary = summarizeTraffic([...merged.values()], [scan, ...(scans.data ?? []).filter(s => s.payload.pool === token.pairAddress).map(s => s.payload)], at, token.pairAddress, { holderAt: cache.data?.updated_at, wallets: cache.data?.payload?.balances ? new Set(cache.data.payload.balances.map((h) => h.wallet)) : undefined, linkedWallets: linked }, (prior.data?.length ?? 0) >= 1000);
    const write = await db.from('api_cache').upsert({ cache_key: `intelligence:traffic:${token.mint}`, payload: summary, updated_at: at });
    if (write.error)
        throw write.error;
    return summary;
}
/** One FIFO requested token plus a fair rotation within the existing budget. */
export function selectHolderWork(tokens, priorityMints, cursor, budget) {
    const priority = priorityMints.map(m => tokens.find(t => t.mint === m)).filter((t) => !!t).slice(0, 1);
    const rotating = tokens.filter(t => !priority.some(p => p.mint === t.mint));
    const start = Number.isFinite(cursor) ? Math.max(0, Math.floor(cursor)) % Math.max(1, rotating.length) : 0;
    const candidates = [...priority];
    for (let i = 0; i < rotating.length && candidates.length < budget; i++)
        candidates.push(rotating[(start + i) % rotating.length]);
    return { priority, rotating, candidates: candidates.slice(0, budget) };
}
import { randomUUID } from 'node:crypto';
export async function ingestMarket() {
    const ingestionStarted = Date.now();
    const db = admin(), lease = randomUUID();
    const claim = await db.rpc('claim_market_ingestion', { p_lease: lease });
    if (claim.error)
        throw claim.error;
    if (!claim.data)
        return { skipped: true, reason: 'Ingestion already running' };
    let lastSuccessAt = null;
    try {
        const status = await db.from('api_cache').select('payload').eq('cache_key', 'worker:status').maybeSingle();
        const lastStatus = status.data?.payload ?? {};
        lastSuccessAt = lastStatus.lastSuccessAt ?? null;
        const statusStart = await db.from('api_cache').upsert({ cache_key: 'worker:status', payload: { state: 'running', startedAt: new Date(ingestionStarted).toISOString(), lastSuccessAt }, updated_at: new Date().toISOString() });
        if (statusStart.error)
            throw statusStart.error;
        const storage = await db.rpc('enforce_market_storage_limit');
        if (storage.error)
            throw storage.error;
        const { data: cached, error } = await db.from('api_cache').select('payload').eq('cache_key', 'market:snapshot').maybeSingle();
        if (error)
            throw error;
        const previous = cached?.payload;
        const tracked = await db.from('tokens').select('mint').order('metadata_updated_at', { ascending: false, nullsFirst: false }).limit(20);
        if (tracked.error)
            throw tracked.error;
        const priorities = await db.from('holder_priorities').select('mint,requested_at').gt('expires_at', new Date().toISOString()).order('requested_at', { ascending: true }).limit(20);
        if (priorities.error)
            throw priorities.error;
        const wanted = (priorities.data ?? []).map(p => p.mint);
        const trackedMints = [...new Set([...wanted, ...(tracked.data ?? []).map(t => t.mint)])].slice(0, 20);
        const base = await collectMarket(previous, trackedMints);
        const prevTokens = new Map((previous?.tokens ?? []).map((t) => [t.mint, t]));
        const mints = base.tokens.map(t => t.mint);
        const { data: holders, error: holderError } = await db.from('api_cache').select('cache_key,payload,updated_at').in('cache_key', mints.map(m => `intelligence:holders:${m}`));
        if (holderError)
            throw holderError;
        const observations = new Map((holders ?? []).map(h => [h.cache_key.split(':').at(-1), h.payload.metrics]));
        const holderCeiling = Math.min(6, Math.max(0, Number(process.env.MARKET_HOLDER_BUDGET ?? 3) || 0));
        const stablePrevious = Number(lastStatus.durationMs ?? Infinity) < 20000 && Number(lastStatus.holderFailures ?? 1) === 0 && Number(lastStatus.trafficFailures ?? 1) === 0;
        const budget = Math.min(holderCeiling, stablePrevious ? 3 : 2);
        const cursor = Number(previous?.holderCursor ?? 0) % Math.max(1, mints.length);
        const failures = [];
        const trackedSet = new Set(trackedMints);
        const work = selectHolderWork(base.tokens.filter(t => trackedSet.has(t.mint)), wanted, cursor, budget);
        const { priority, rotating: rotation, candidates } = work;
        let completed = 0;
        for (const t of candidates.slice(0, budget)) {
            if (Date.now() - ingestionStarted > 55_000)
                break;
            try {
                observations.set(t.mint, await observeHolders(t.mint, t.priceUsd));
                const requested = (priorities.data ?? []).find(p => p.mint === t.mint);
                if (requested) {
                    const removed = await db.from('holder_priorities').delete().eq('mint', t.mint).lte('requested_at', requested.requested_at);
                    if (removed.error)
                        throw removed.error;
                }
            }
            catch {
                failures.push(t.mint);
            }
            completed++;
        }
        // Traffic stays on the worker, under a global time and RPC budget.
        const trafficUniverse = base.tokens.filter(t => trackedSet.has(t.mint) && t.pairAddress).slice(0, 20);
        const trafficCeiling = Math.min(6, Math.max(0, Number(process.env.MARKET_TRAFFIC_BUDGET ?? 3) || 0)), trafficBudget = Math.min(trafficCeiling, stablePrevious ? 3 : 2);
        const trafficWork = selectHolderWork(trafficUniverse, wanted, Number(previous?.trafficCursor ?? 0), trafficBudget);
        const trafficCandidates = trafficWork.candidates;
        let trafficCompleted = 0, trafficFailures = 0;
        const trafficByMint = new Map();
        const trafficCache = await db.from('api_cache').select('cache_key,payload').in('cache_key', mints.map(m => `intelligence:traffic:${m}`));
        if (trafficCache.error)
            throw trafficCache.error;
        for (const row of trafficCache.data ?? [])
            trafficByMint.set(row.cache_key.split(':').at(-1), row.payload);
        const solMarket = trafficCandidates.length ? await fetchDexScreenerToken(WSOL_MINT).catch(() => null) : null;
        for (let i = 0; i < Math.min(trafficBudget, trafficCandidates.length) && Date.now() - ingestionStarted < 90000; i++) {
            const t = trafficCandidates[i];
            try {
                trafficByMint.set(t.mint, await observeTraffic(t, solMarket?.priceUsd ?? null, observations.get(t.mint), ingestionStarted + 110000));
            }
            catch {
                trafficFailures++;
            }
            trafficCompleted++;
        }
        const at = new Date().toISOString();
        const baselines = await db.rpc('market_window_baselines', { p_mints: mints, p_at: at });
        if (baselines.error)
            throw baselines.error;
        const tokens = base.tokens.map(t => {
            const holder = observations.get(t.mint);
            const fresh = holder?.holderObservedAt && Date.now() - Date.parse(holder.holderObservedAt) < 60 * 60_000;
            const metrics = fresh ? holder : { holderCount: null, holderGrowth: null, holderGrowthPct: null, freshWallets: null, top10SupplyPct: null, linkedWallets: null, suspiciousWallets: null, whaleEnter: null, whaleExit: null, smartMoneyFlowUsd: null, holderObservedAt: holder?.holderObservedAt ?? null };
            if (!fresh)
                Object.assign(metrics, { newHolders: null, exitedHolders: null, largestHolderPct: null, whaleConcentrationPct: null, linkedSupplyPct: null, holderWindows: {}, topHolderSales: [] });
            const sample = trafficByMint.get(t.mint);
            const enriched = { ...t, ...metrics, trafficSample: sample?.pool === t.pairAddress ? sample : null };
            return { ...enriched, windows: compareMarketWindows(enriched, at, (baselines.data ?? [])), ...deriveSignals(enriched, prevTokens.get(t.mint), at, previous?.fetchedAt),
                // Directional volume estimate based on trade counts, not measured capital transfers.
                netFlowUsd1h: t.volume1h * (t.buys1h - t.sells1h) / Math.max(1, t.trades1h) };
        });
        const [history, cooldownHistory] = await Promise.all([
            db.from('market_alerts').select('payload').gte('observed_at', new Date(Date.now() - 24 * 60 * 60_000).toISOString()).order('observed_at', { ascending: false }).limit(80),
            db.from('market_alerts').select('payload').gte('observed_at', new Date(Date.now() - 30 * 60_000).toISOString()).order('observed_at', { ascending: false }).limit(500)
        ]);
        if (history.error || cooldownHistory.error)
            throw history.error ?? cooldownHistory.error;
        const historicalAlerts = (history.data ?? []).map(r => r.payload), cooldownAlerts = (cooldownHistory.data ?? []).map(r => r.payload), alerts = prioritizeAlerts(suppressRepeatedAlerts(tokens.flatMap(t => evaluateAlerts(t, prevTokens.get(t.mint), at)), cooldownAlerts));
        const recentAlerts = collapseAlertHistory([...alerts, ...historicalAlerts]).slice(0, 80);
        const payload = { ...base, tokens, fetchedAt: at, holderCursor: (cursor + Math.max(0, completed - priority.length)) % Math.max(1, rotation.length),
            trafficCursor: (Number(previous?.trafficCursor ?? 0) + Math.max(0, trafficCompleted - trafficWork.priority.length)) % Math.max(1, trafficWork.rotating.length), alerts: recentAlerts, recentEvents: base.recentEvents,
            storage: storage.data, ingestion: { trafficCompleted, trafficFailures, trafficUniverse: trafficUniverse.length, trafficBudget, holderCompleted: completed, priorityMints: priority.map(t => t.mint), holderBudget: budget, holderFailures: failures.length, source: 'server-worker', interval: '5m target; scheduler dependent' },
            metricNotes: { flow: 'USD estimate from rolling 1h trade counts', freshWallets: 'newly observed token holders; not wallet creation age', whales: 'owners ≥1% supply; pool/program owners included', smartMoney: 'whale balance change at current price; not verified swap flow', volumeAcceleration: 'acceleration of rolling 1h volume, USD/min²', risk: 'heuristic, not a security audit' } };
        const saved = await db.rpc('commit_market_snapshot', { p_lease: lease, p_payload: payload, p_alerts: alerts });
        if (saved.error)
            throw saved.error;
        const finishedAt = new Date().toISOString();
        const statusDone = await db.from('api_cache').upsert({ cache_key: 'worker:status', payload: { state: 'ok', startedAt: new Date(ingestionStarted).toISOString(), finishedAt, lastSuccessAt: at, durationMs: Date.now() - ingestionStarted, holderFailures: failures.length, trafficFailures, holderCompleted: completed, trafficCompleted, tokens: tokens.length, recentHolders: tokens.filter(t => t.holderObservedAt && Date.now() - Date.parse(t.holderObservedAt) < 3600000).length, recentTraffic: tokens.filter(t => t.trafficObservedAt && Date.now() - Date.parse(t.trafficObservedAt) < 600000).length, usableTraffic: tokens.filter(t => t.trafficEvidence === 'usable' && t.trafficObservedAt && Date.now() - Date.parse(t.trafficObservedAt) < 600000).length, holderBudget: budget, trafficBudget, trafficDiagnostics: tokens.reduce((acc, t) => { for (const [k, v] of Object.entries(t.trafficSample?.failures ?? {}))
                    acc[k] = (acc[k] ?? 0) + Number(v); return acc; }, {}), priorityMints: priority.map(t => t.mint) }, updated_at: finishedAt });
        if (statusDone.error)
            throw statusDone.error;
        return { ok: true, tokens: tokens.length, alerts: alerts.length, holderFailures: failures.length, fetchedAt: at };
    }
    catch (error) {
        await db.from('api_cache').upsert({ cache_key: 'worker:status', payload: { state: 'error', startedAt: new Date(ingestionStarted).toISOString(), finishedAt: new Date().toISOString(), lastSuccessAt, error: 'Background ingestion failed; previous market cache retained' }, updated_at: new Date().toISOString() });
        throw error;
    }
    finally {
        await db.rpc('release_market_ingestion', { p_lease: lease });
    }
}
const rpc = solanaRpc;
Deno.serve(async (req) => {
    if (req.method !== 'POST')
        return new Response('Method not allowed', { status: 405 });
    const provided = req.headers.get('authorization') ?? '';
    if (!/^Bearer [a-f0-9-]{72}$/.test(provided))
        return new Response('Unauthorized', { status: 401 });
    const { data, error } = await admin().from('market_worker_config').select('secret').eq('id', 1).single();
    const expected = 'Bearer ' + (data?.secret ?? '');
    if (error || Buffer.byteLength(provided) !== Buffer.byteLength(expected) || !timingSafeEqual(Buffer.from(provided), Buffer.from(expected)))
        return new Response('Unauthorized', { status: 401 });
    try {
        return Response.json(await ingestMarket());
    }
    catch (error) {
        console.error('Snapshot worker failed', error instanceof Error ? error.message : 'upstream/database error');
        return Response.json({ error: 'Snapshot worker failed; previous cache retained' }, { status: 502 });
    }
});
